import { execFileSync } from 'node:child_process'
import { test, expect } from '@playwright/test'

test('human approval queue requires step-up and records approve/revoke without sending', async ({ page }, testInfo) => {
  const python = process.env.PYTHON || (process.platform === 'win32' ? '../backend/.venv/Scripts/python.exe' : '../backend/.venv/bin/python')
  const fixture = JSON.parse(execFileSync(python, ['../backend/tests/e2e_user.py', 'approval-fixture'], { env: process.env, encoding: 'utf8' })) as { project_id: string; company_id: string }
  const forbidden: string[] = []
  page.on('request', request => { if (/\/send|\/execute|\/test-send|\/dispatch/.test(request.url())) forbidden.push(request.url()) })
  await page.goto('/')
  await page.getByLabel('メールアドレス').fill(process.env.E2E_EMAIL!)
  await page.getByLabel('パスワード').fill(process.env.E2E_PASSWORD!)
  await page.getByRole('button', { name: 'ログインする', exact: true }).click()
  const guide = page.getByRole('dialog', { name: '3ステップで始めましょう' })
  await expect(guide).toBeVisible()
  await guide.getByRole('button', { name: 'あとで見る' }).click()
  await page.getByRole('button', { name: '✓ 承認キュー', exact: true }).click()
  await page.getByLabel('承認プロジェクト').selectOption(fixture.project_id)
  await page.getByRole('button', { name: '承認待ち提案を作成', exact: true }).click()
  await page.getByLabel('提案先の会社').selectOption(fixture.company_id)
  await page.getByLabel('宛先メール').fill('recipient@example.com')
  await page.getByLabel('送信者名').fill('A2 Human')
  await page.getByLabel('送信者メール').fill('sender@example.com')
  await page.getByLabel('件名', { exact: true }).fill('Approval snapshot')
  await page.getByLabel('本文', { exact: true }).fill('A2 does not send this message.')
  await page.getByRole('button', { name: '提案を保存', exact: true }).click()
  await page.getByRole('button', { name: /A2 E2E Company.*承認待ち/ }).click()
  await expect(page.getByText('A2 does not send this message.', { exact: true })).toBeVisible()
  await page.getByLabel('承認用パスワード（再認証）').fill('wrong-password')
  await page.getByRole('button', { name: '内容を確認して承認', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('再認証に失敗')
  await page.getByLabel('承認用パスワード（再認証）').fill(process.env.E2E_PASSWORD!)
  await page.getByRole('button', { name: '内容を確認して承認', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('送信は行っていません')
  await expect(page.getByRole('button', { name: /A2 E2E Company.*承認済み/ })).toBeVisible()
  await expect(page.getByRole('button', { name: '送信', exact: true })).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: testInfo.outputPath('human-approval.png'), fullPage: true })
  await page.getByLabel('却下・取消の理由').fill('Review cancelled')
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await expect(page.getByRole('button', { name: /A2 E2E Company.*取消済み/ })).toBeVisible()
  await page.getByText('監査記録（最新100件）', { exact: true }).click()
  await expect(page.getByText(/approval granted/)).toBeVisible()
  const proposal = await page.request.post(`/api/projects/${fixture.project_id}/approval-requests`, { data: {
    company_id: fixture.company_id, channel: 'email', delivery_method: 'email', recipient: 'recipient@example.com',
    subject: 'Reject this proposal', body: 'Human review required', sender: { name: 'Human', email: 'sender@example.com' },
  } })
  expect(proposal.status()).toBe(201)
  await page.getByRole('button', { name: '最新の状態を取得', exact: true }).click()
  await page.getByRole('button', { name: /A2 E2E Company.*承認待ち/ }).click()
  await page.getByLabel('却下・取消の理由').fill('Not appropriate')
  await page.getByRole('button', { name: '却下', exact: true }).click()
  await expect(page.getByRole('button', { name: /A2 E2E Company.*却下/ })).toBeVisible()
  const member = await page.request.post(`/api/projects/${fixture.project_id}/members`, { data: { email: process.env.E2E_MEMBER_EMAIL!, role: 'viewer' } })
  expect(member.ok()).toBeTruthy()
  await page.getByRole('button', { name: 'ログアウト', exact: true }).click()
  await page.getByLabel('メールアドレス').fill(process.env.E2E_MEMBER_EMAIL!)
  await page.getByLabel('パスワード').fill(process.env.E2E_MEMBER_PASSWORD!)
  await page.getByRole('button', { name: 'ログインする', exact: true }).click()
  await expect(guide).toBeVisible()
  await guide.getByRole('button', { name: 'あとで見る' }).click()
  await page.getByRole('button', { name: '✓ 承認キュー', exact: true }).click()
  await page.getByLabel('承認プロジェクト').selectOption(fixture.project_id)
  await expect(page.getByRole('button', { name: /A2 E2E Company.*却下/ })).toBeVisible()
  await expect(page.getByRole('button', { name: '承認待ち提案を作成', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '内容を確認して承認', exact: true })).toHaveCount(0)
  expect(forbidden).toEqual([])
})
