import { navigateWorkspace } from './navigation'
import { execFileSync } from 'node:child_process'
import { randomBytes } from 'node:crypto'
import { test, expect } from '@playwright/test'

test('Human freezes the funnel denominator and records review effort without approval or sending', async ({ page }) => {
  test.setTimeout(120_000)
  const python = process.env.PYTHON || (process.platform === 'win32' ? '../backend/.venv/Scripts/python.exe' : '../backend/.venv/bin/python')
  const env = { ...process.env, E2E_EMAIL: `e2e-metrics-${randomBytes(8).toString('hex')}@example.com`, E2E_PASSWORD: randomBytes(24).toString('hex') }
  execFileSync(python, ['../backend/tests/e2e_user.py', 'create'], { env })
  const forbidden: string[] = []
  page.on('request', request => {
    if (!['localhost', '127.0.0.1'].includes(new URL(request.url()).hostname) || /\/send(?:[/?]|$)|\/dispatch|\/execute|\/test-send|\/approve/.test(request.url())) forbidden.push(request.url())
  })
  try {
    const fixture = JSON.parse(execFileSync(python, ['../backend/tests/e2e_user.py', 'completion-fixture'], { env, encoding: 'utf8' })) as { project_id: string }
    await page.goto('/')
    await page.getByLabel('メールアドレス').fill(env.E2E_EMAIL)
    await page.getByLabel('パスワード').fill(env.E2E_PASSWORD)
    await page.getByRole('button', { name: 'ログインする', exact: true }).click()
    await page.getByRole('dialog', { name: '3ステップで始めましょう' }).getByRole('button', { name: 'あとで見る' }).click()
    await navigateWorkspace(page, '⌂ ダッシュボード')
    const panel = page.getByRole('region', { name: 'Lead Completion計測' })
    await panel.getByLabel('完成率のプロジェクト').selectOption(fixture.project_id)
    await panel.getByRole('button', { name: '現在のリストを集計対象として固定', exact: true }).click()
    await expect(panel).toContainText('DM READY率')
    await expect(panel).toContainText('未判定')
    await expect(panel).toContainText('料金・Cost per DM READYは不明')
    const diagnostic = panel.getByRole('region', { name: '固定リストの窓口診断' })
    let release: () => void = () => {}
    const gate = new Promise<void>(resolve => { release = resolve })
    let hold = true
    let syntheticUnknown = false
    await page.route('**/destination-diagnostics?*', async route => {
      if (new URL(route.request().url()).searchParams.get('offset') === '25' && hold) { hold = false; await gate }
      if (syntheticUnknown && new URL(route.request().url()).searchParams.get('offset') === '0') {
        // Response-only safety fixture; no send or database history is fabricated.
        const response = await route.fetch()
        const batch = await response.json()
        batch.rows[0].reasons.push({ code: 'SYNTHETIC_REVIEW', message: 'Synthetic review observation', next_action: 'Synthetic Human review' })
        batch.rows[0].delivery_funnel = { prepared_ever: true, human_approved: true, sent: true, attempt_count: 1, results: { ACCEPTED: 0, DELIVERED: 0, UNKNOWN: 1, FAILED: 0, IN_PROGRESS: 0 }, queued: 0, blocked: 0, cancelled: 0, preflight_failed: 0, unverified_records: 0 }
        batch.rows[1].company_name = null
        batch.rows[1].reasons = [{ code: 'LEAD_REMOVED_OR_MERGED', message: '削除・統合された候補', next_action: '現在の対象を確認する' }]
        await route.fulfill({ response, json: batch })
      } else await route.continue()
    })
    await diagnostic.getByRole('button', { name: '窓口診断を集計', exact: true }).click()
    await expect(diagnostic).toContainText('診断済み 25 / 26件')
    await expect(diagnostic).toContainText('部分集計・未診断分あり')
    const queue = diagnostic.getByRole('region', { name: 'Lead Completion作業キュー' })
    const benchmark = diagnostic.getByRole('region', { name: 'Lead Completion Benchmark' })
    await expect(benchmark).toContainText('部分集計・変換率は未判定')
    await expect(benchmark).toContainText('unknown / null')
    await expect(queue).toContainText('部分集計・未診断分を含みません')
    await expect(queue).toContainText('作業対象 25件 / 診断済み 25件')
    await diagnostic.getByRole('button', { name: '窓口集計を中断', exact: true }).click()
    release()
    await expect(diagnostic).toContainText('診断済み 25 / 26件')
    await diagnostic.getByRole('button', { name: '窓口診断を集計', exact: true }).click()
    await expect(diagnostic).toContainText('診断済み 26 / 26件 — 全件集計済み')
    await expect(diagnostic).toContainText('READY 0 / REVIEW 0 / HOLD 26 / BLOCKED 0')
    await expect(diagnostic).toContainText('公式サイト未登録：25件')
    await expect(diagnostic).toContainText('診断範囲のDM READY：0件 / DM READY率：0.0%')
    const history = diagnostic.getByRole('region', { name: 'Human承認と送信結果のFunnel' })
    await expect(history).toContainText('提案準備済み 0 Lead → Human承認記録 0 Lead → 送信実行 0 Lead')
    await expect(history).toContainText('送信試行 0件')
    await expect(history).toContainText('メール到達証跡あり：0件')
    await expect(history).toContainText('旧経路の履歴を推定して混ぜません')
    await expect(diagnostic.locator('article').filter({ hasText: '診断範囲の共通窓口' })).toContainText('1')
    await expect(diagnostic.locator('article').filter({ hasText: 'READYの独立窓口' })).toContainText('0')
    await expect(benchmark).toContainText('全件観察済み')
    await expect(benchmark).toContainText('Before / Current')
    await expect(benchmark).toContainText('Cost per DM READY unknown / null')
    await benchmark.getByRole('button', { name: 'DM_NOT_PREPARED', exact: true }).click()
    await expect(queue.getByLabel('作業キューの停止理由')).toHaveValue('DM_NOT_PREPARED')
    await expect(queue).toContainText('作業対象 26件 / 診断済み 26件')
    await queue.getByLabel('作業キューの停止理由').selectOption('ALL')
    await expect(queue).toContainText('作業対象 26件 / 診断済み 26件')
    await expect(queue.getByRole('article')).toHaveCount(25)
    await queue.getByRole('button', { name: '次の25件', exact: true }).click()
    await expect(queue.getByRole('article')).toHaveCount(1)
    await queue.getByLabel('作業キューの停止理由').selectOption({ label: '公式サイト未登録（25件）' })
    await expect(queue).toContainText('作業対象 25件 / 診断済み 26件（1 / 1ページ')
    await queue.getByLabel('作業キューの状態').selectOption('DM_READY')
    await expect(queue).toContainText('該当する診断済み候補はありません')
    await queue.getByLabel('作業キューの状態').selectOption('DM_NOT_READY')
    await expect(queue.getByRole('article')).toHaveCount(25)
    await panel.getByLabel('レビュー時間を記録する企業').selectOption({ index: 1 })
    await panel.getByRole('button', { name: 'レビュー時間の記録を開始', exact: true }).click()
    await expect(panel.getByRole('status').filter({ hasText: 'レビュー計測中' })).toContainText('レビュー計測中')
    await page.reload()
    await navigateWorkspace(page, '⌂ ダッシュボード')
    await panel.getByLabel('完成率のプロジェクト').selectOption(fixture.project_id)
    await panel.getByLabel('固定した集計対象').selectOption({ index: 1 })
    await expect(panel.getByRole('status').filter({ hasText: 'レビュー計測中' })).toContainText('レビュー計測中')
    await panel.getByRole('button', { name: 'レビュー記録を終了', exact: true }).click()
    await expect(panel).toContainText('レビュー 1 / 1件終了')
    await expect(panel).toContainText('営業許可・Human承認を変更しません')
    syntheticUnknown = true
    await diagnostic.getByRole('button', { name: '窓口診断を集計', exact: true }).click()
    await expect(queue).toContainText('作業対象 26件 / 診断済み 26件')
    await expect(queue.getByRole('article').nth(1).getByRole('button', { name: '詳細を開く', exact: true })).toBeDisabled()
    await queue.getByLabel('作業キューの状態').selectOption('DELIVERY_REVIEW')
    await expect(queue).toContainText('作業対象 1件 / 診断済み 26件')
    await expect(queue).toContainText('Human確認が必要です。自動再送しません')
    await queue.getByLabel('作業キューの停止理由').selectOption('SYNTHETIC_REVIEW')
    const fixedCohortId = await panel.getByLabel('固定した集計対象').inputValue()
    const candidate = queue.getByRole('article').first()
    const companyName = await candidate.locator('strong').innerText()
    await candidate.getByRole('button', { name: '詳細を開く', exact: true }).click()
    await expect(page.getByRole('heading', { name: companyName, exact: true })).toBeVisible()
    await page.getByRole('button', { name: '作業キューへ戻る', exact: true }).click()
    await expect(panel.getByLabel('完成率のプロジェクト')).toHaveValue(fixture.project_id)
    await expect(panel.getByLabel('固定した集計対象')).toHaveValue(fixedCohortId)
    await expect(panel).toContainText('以前の診断結果は引き継ぎません')
    await expect(diagnostic).toContainText('診断済み 0 / 26件')
    await expect(queue).toHaveCount(0)
    syntheticUnknown = false
    await diagnostic.getByRole('button', { name: '窓口診断を集計', exact: true }).click()
    await expect(diagnostic).toContainText('診断済み 26 / 26件 — 全件集計済み')
    await expect(queue.getByLabel('作業キューの状態')).toHaveValue('DELIVERY_REVIEW')
    await expect(queue).toContainText('作業対象 0件 / 診断済み 26件')
    await expect(queue.getByLabel('作業キューの停止理由')).toHaveValue('SYNTHETIC_REVIEW')
    await expect(queue.getByLabel('作業キューの停止理由')).toContainText('以前の理由・今回の診断範囲に該当なし')
    await queue.getByLabel('作業キューの停止理由').selectOption('ALL')
    await queue.getByLabel('作業キューの状態').selectOption('HOLD')
    await queue.getByRole('button', { name: '次の25件', exact: true }).click()
    await expect(queue).toContainText('2 / 2ページ')
    const lastCandidate = queue.getByRole('article').first()
    const lastCompanyName = await lastCandidate.locator('strong').innerText()
    await lastCandidate.getByRole('button', { name: '詳細を開く', exact: true }).click()
    const detail = page.getByRole('region', { name: '企業詳細', exact: true })
    await expect(detail.getByRole('heading', { name: lastCompanyName, exact: true })).toBeVisible()
    await page.getByRole('button', { name: '作業キューへ戻る', exact: true }).click()
    await expect(diagnostic).toContainText('診断済み 0 / 26件')
    await diagnostic.getByRole('button', { name: '窓口診断を集計', exact: true }).click()
    await expect(diagnostic).toContainText('診断済み 26 / 26件 — 全件集計済み')
    await expect(queue).toContainText('2 / 2ページ')
    await expect(queue.getByRole('article')).toHaveCount(1)
    await queue.getByRole('article').first().getByRole('button', { name: '詳細を開く', exact: true }).click()
    await expect(detail.getByRole('heading', { name: lastCompanyName, exact: true })).toBeVisible()
    await detail.getByLabel('この企業への連絡を禁止', { exact: true }).check()
    await detail.getByLabel('除外理由', { exact: true }).fill('Synthetic Human contact restriction')
    await detail.getByRole('button', { name: '連絡制御を保存', exact: true }).click()
    await expect(page.getByText('連絡制御と連絡先品質を保存しました。', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: '作業キューへ戻る', exact: true }).click()
    await expect(diagnostic).toContainText('診断済み 0 / 26件')
    await diagnostic.getByRole('button', { name: '窓口診断を集計', exact: true }).click()
    await expect(diagnostic).toContainText('診断済み 26 / 26件 — 全件集計済み')
    await expect(diagnostic).toContainText('HOLD 1 / BLOCKED 25')
    await expect(diagnostic).toContainText('送信禁止リストに登録済み：24件')
    await expect(queue.getByLabel('作業キューの状態')).toHaveValue('HOLD')
    await expect(queue).toContainText('作業対象 1件 / 診断済み 26件（1 / 1ページ')
    await expect(queue.getByRole('article', { name: `作業候補 ${lastCompanyName}`, exact: true })).toHaveCount(0)
    await queue.getByLabel('作業キューの状態').selectOption('BLOCKED')
    await expect(queue.getByRole('article', { name: `作業候補 ${lastCompanyName}`, exact: true })).toBeVisible()
    // A failed re-read must not fall back to the old successful diagnostics.
    await page.route('**/destination-diagnostics?*', route => route.fulfill({ status: 403, json: { detail: 'Synthetic read denied' } }))
    await diagnostic.getByRole('button', { name: '窓口診断を集計', exact: true }).click()
    await expect(diagnostic.getByRole('alert')).toContainText('完了扱いにはしません')
    await expect(diagnostic).toContainText('診断済み 0 / 26件')
    await expect(queue).toHaveCount(0)
    await expect(benchmark).toHaveCount(0)
    await page.unroute('**/destination-diagnostics?*')
    await page.route(`**/api/completion-cohorts/${fixedCohortId}`, async route => {
      const response = await route.fetch()
      const report = await response.json()
      await route.fulfill({ response, json: { ...report, discovered: 0, remaining_leads: 0 } })
    })
    let invalidBenchmark = false
    await page.route('**/destination-diagnostics?*', async route => {
      const response = await route.fetch()
      const batch = await response.json()
      await route.fulfill({ response, json: { ...batch, discovered: 0, inspected: 0, offset: 0, next_offset: null, rows: [], benchmark_meta: { ...batch.benchmark_meta, definition: invalidBenchmark ? 'invalid' : 'completion-benchmark-v1' } } })
    })
    await page.reload()
    await navigateWorkspace(page, '⌂ ダッシュボード')
    await panel.getByLabel('完成率のプロジェクト').selectOption(fixture.project_id)
    await panel.getByLabel('固定した集計対象').selectOption(fixedCohortId)
    await expect(diagnostic).toContainText('診断済み 0 / 0件')
    await diagnostic.getByRole('button', { name: '窓口診断を集計', exact: true }).click()
    await expect(benchmark).toContainText('固定分母 0件 / 観察 0件')
    await expect(benchmark).toContainText('unknown / null')
    await expect(queue).toContainText('該当する診断済み候補はありません')
    invalidBenchmark = true
    await diagnostic.getByRole('button', { name: '窓口診断を集計', exact: true }).click()
    await expect(diagnostic.getByRole('alert')).toContainText('Benchmarkの証跡を確認できません')
    await expect(benchmark).toHaveCount(0)
    expect(forbidden).toEqual([])
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  } finally {
    execFileSync(python, ['../backend/tests/e2e_user.py', 'cleanup'], { env })
  }
})
