import { execFileSync } from 'node:child_process'
import { randomBytes } from 'node:crypto'
import { test, expect } from '@playwright/test'

test('Human can prepare evidence template draft without sending and changed destination requires review', async ({ page }) => {
  const python = process.env.PYTHON || (process.platform === 'win32' ? '../backend/.venv/Scripts/python.exe' : '../backend/.venv/bin/python')
  const env = { ...process.env, E2E_EMAIL: `e2e-completion-${randomBytes(8).toString('hex')}@example.com`, E2E_PASSWORD: randomBytes(24).toString('hex') }
  execFileSync(python, ['../backend/tests/e2e_user.py', 'create'], { env })
  const forbidden: string[] = []
  page.on('request', request => {
    if (!['localhost', '127.0.0.1'].includes(new URL(request.url()).hostname) || /\/(?:send|dispatch|execute|test-send|approve)(?:[/?]|$)/.test(request.url())) forbidden.push(request.url())
  })
  try {
    const fixture = JSON.parse(execFileSync(python, ['../backend/tests/e2e_user.py', 'destination-selection-fixture'], { env, encoding: 'utf8' })) as { project_id: string }
    await page.goto('/')
    await page.getByLabel('メールアドレス').fill(env.E2E_EMAIL)
    await page.getByLabel('パスワード').fill(env.E2E_PASSWORD)
    await page.getByRole('button', { name: 'ログインする', exact: true }).click()
    await page.getByRole('dialog', { name: '3ステップで始めましょう' }).getByRole('button', { name: 'あとで見る' }).click()
    await page.getByRole('button', { name: '▤ 企業一覧', exact: true }).click()
    await page.getByRole('combobox', { name: 'プロジェクト', exact: true }).selectOption(fixture.project_id)
    await page.getByRole('button', { name: '詳細', exact: true }).first().click()
    const panel = page.getByRole('region', { name: 'リスト完成の根拠' })
    await panel.getByRole('button', { name: 'プロジェクトの窓口候補を整理', exact: true }).click()
    const assessment = panel.getByRole('region', { name: '窓口の利用可否と理由' })
    await expect(assessment).toContainText('DESTINATION_PURPOSE_UNCERTAIN')
    await assessment.locator('summary').click()
    await assessment.getByRole('combobox', { name: '窓口用途', exact: true }).selectOption('business')
    await assessment.getByRole('combobox', { name: '窓口の対象範囲', exact: true }).selectOption('company')
    await assessment.getByLabel('用途の根拠URL', { exact: true }).fill('https://approval.example/contact')
    await assessment.getByLabel('公開ページの用途説明', { exact: true }).fill('事業提携などのご相談はこちらで受け付けます。')
    await assessment.getByRole('button', { name: '用途確認を記録', exact: true }).click()
    await expect(assessment).toContainText('判定：準備候補（READY）')
    const choice = assessment.getByRole('region', { name: '営業準備に使う窓口の選択' })
    await choice.getByRole('button', { name: /この窓口を準備対象に選択/ }).click()
    await expect(choice).toContainText('有効（CURRENT） / 記録版 1')
    const dm = panel.getByRole('region', { name: '根拠付きDM下書き準備' })
    await dm.getByText('基本文面テンプレートを作成', { exact: true }).click()
    await dm.getByLabel('基本文面の名前', { exact: true }).fill('Synthetic evidence template')
    await dm.getByLabel('基本文面の件名', { exact: true }).fill('Synthetic subject')
    await dm.getByLabel('サービス説明・提案・CTA・署名', { exact: true }).fill('サービスのご紹介です。ご関心がありましたらご返信ください。Synthetic Sender')
    await dm.getByRole('button', { name: '基本文面を登録', exact: true }).click()
    await expect(dm.getByRole('combobox', { name: 'DMの基本文面', exact: true })).toContainText('Synthetic evidence template')
    await dm.getByLabel('個別情報の根拠URL', { exact: true }).fill('https://approval.example/services')
    await dm.getByLabel('確認した公開情報の引用', { exact: true }).fill('当社は公開のサービス紹介を掲載しています。')
    await dm.getByLabel('DMに使う事実', { exact: true }).fill('公開のサービス紹介を掲載しています')
    const save = dm.getByRole('button', { name: '根拠付き下書きを保存', exact: true })
    await expect(save).toBeDisabled()
    await dm.getByLabel('この公式ページで事実と引用を確認しました', { exact: true }).check()
    await save.click()
    const saved = dm.getByRole('article', { name: '保存した根拠付き下書き' })
    await expect(saved).toContainText('下書き準備済み（DRAFT_PREPARED）')
    await expect(saved).toContainText('公開情報で「公開のサービス紹介を掲載しています」を拝見しました。')
    await expect(saved.getByRole('link')).toHaveAttribute('href', 'https://approval.example/services')
    await expect(dm).toContainText('DM READY・送信承認・送信には進みません')
    await page.reload()
    await page.getByRole('button', { name: '▤ 企業一覧', exact: true }).click()
    await page.getByRole('combobox', { name: 'プロジェクト', exact: true }).selectOption(fixture.project_id)
    await page.getByRole('button', { name: '詳細', exact: true }).first().click()
    await expect(saved).toContainText('下書き準備済み（DRAFT_PREPARED）')
    await page.getByLabel('メール', { exact: true }).fill('changed-destination@example.com')
    await page.getByRole('button', { name: '企業情報を保存', exact: true }).click()
    await expect(saved).toContainText('要再確認（REVIEW）：窓口選択・安全条件の変更')
    await expect(dm.getByRole('button', { name: '根拠付き下書きを保存', exact: true })).toHaveCount(0)
    await expect(panel.getByRole('button', { name: /送信|承認/ })).toHaveCount(0)
    expect(forbidden).toEqual([])
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  } finally {
    execFileSync(python, ['../backend/tests/e2e_user.py', 'cleanup'], { env })
  }
})
