import { execFileSync } from 'node:child_process'
import { randomBytes } from 'node:crypto'
import { test, expect } from '@playwright/test'

test('Human can organize candidate destinations without approval or sending', async ({ page }) => {
  const python = process.env.PYTHON || (process.platform === 'win32' ? '../backend/.venv/Scripts/python.exe' : '../backend/.venv/bin/python')
  const env = { ...process.env, E2E_EMAIL: `e2e-completion-${randomBytes(8).toString('hex')}@example.com`, E2E_PASSWORD: randomBytes(24).toString('hex') }
  execFileSync(python, ['../backend/tests/e2e_user.py', 'create'], { env })
  const forbidden: string[] = []
  page.on('request', request => {
    if (!['localhost', '127.0.0.1'].includes(new URL(request.url()).hostname) || /\/(?:send|dispatch|execute|test-send|approve)(?:[/?]|$)/.test(request.url())) forbidden.push(request.url())
  })
  try {
    const fixture = JSON.parse(execFileSync(python, ['../backend/tests/e2e_user.py', 'approval-fixture'], { env, encoding: 'utf8' })) as { project_id: string }
    await page.goto('/')
    await page.getByLabel('メールアドレス').fill(env.E2E_EMAIL)
    await page.getByLabel('パスワード').fill(env.E2E_PASSWORD)
    await page.getByRole('button', { name: 'ログインする', exact: true }).click()
    await page.getByRole('dialog', { name: '3ステップで始めましょう' }).getByRole('button', { name: 'あとで見る' }).click()
    await page.getByRole('button', { name: '▤ 企業一覧', exact: true }).click()
    await page.getByRole('combobox', { name: 'プロジェクト', exact: true }).selectOption(fixture.project_id)
    await page.getByRole('button', { name: '詳細', exact: true }).first().click()
    const panel = page.getByRole('region', { name: 'リスト完成の根拠' })
    await page.getByLabel('メール', { exact: true }).fill('synthetic-recipient@example.com')
    await page.getByLabel('電話', { exact: true }).fill('0791234567')
    await page.getByRole('button', { name: '企業情報を保存', exact: true }).click()
    await expect(panel).toContainText('窓口候補 1件')
    const assessment = panel.getByRole('region', { name: '窓口の利用可否と理由' })
    await expect(assessment).toContainText('判定：要確認（REVIEW）')
    await expect(assessment).toContainText('EMAIL_UNVERIFIED')
    await expect(assessment).toContainText('DESTINATION_PURPOSE_UNCERTAIN')
    await expect(assessment).toContainText('送信承認、送信は行いません')
    await expect(assessment.getByRole('button')).toHaveCount(0)
    await expect(panel).toContainText('企業・店舗の照合：要確認')
    await expect(panel).toContainText('営業許可・DM READY・送信承認を意味しません')
    const identity = panel.locator('details[aria-label="企業・店舗と公式サイトのHuman確認"]')
    await identity.locator('summary').click()
    await expect(identity.getByLabel('照合対象の登録情報')).toContainText('0791234567')
    await expect(identity.getByLabel('公式ページの企業・店舗名', { exact: true })).toHaveValue('')
    await identity.getByLabel('公式ページの企業・店舗名', { exact: true }).fill('A2 E2E Company')
    await identity.getByLabel('公式ページの電話', { exact: true }).fill('079-123-4567')
    await identity.getByLabel('照合の根拠URL', { exact: true }).fill('https://approval.example/about')
    await identity.getByLabel('照合の公開情報', { exact: true }).fill('公式ページの会社名と電話の一致を確認しました。')
    const record = identity.getByRole('button', { name: '照合確認を記録', exact: true })
    const observed = identity.getByLabel('公式ページで名称と住所または電話、および根拠を確認しました', { exact: true })
    await expect(record).toBeDisabled()
    await identity.getByLabel('公式ページの電話', { exact: true }).fill('079-999-9999')
    await identity.getByRole('button', { name: '入力内容の照合をプレビュー', exact: true }).click()
    await expect(identity).toContainText('電話が登録情報と異なります')
    await expect(observed).toBeDisabled()
    await expect(identity).toContainText('Human確認：UNREVIEWED / 記録版 0')
    await identity.getByLabel('公式ページの電話', { exact: true }).fill('079-123-4567')
    await identity.getByRole('button', { name: '入力内容の照合をプレビュー', exact: true }).click()
    await expect(identity).toContainText('まだ確認記録は保存されていません')
    await expect(record).toBeDisabled()
    await observed.check()
    await expect(record).toBeEnabled()
    await identity.getByLabel('照合の公開情報', { exact: true }).fill('公式ページの会社名と電話の一致を再確認しました。')
    await expect(observed).not.toBeChecked()
    await expect(record).toBeDisabled()
    await identity.getByRole('button', { name: '入力内容の照合をプレビュー', exact: true }).click()
    await observed.check()
    await identity.getByRole('button', { name: '照合確認を記録', exact: true }).click()
    await expect(identity).toContainText('Human確認：CURRENT / 記録版 1')
    await expect(panel).toContainText('企業・店舗の照合：照合済み')
    await expect(assessment).not.toContainText('IDENTITY_UNCERTAIN')
    await panel.getByRole('button', { name: 'プロジェクトの窓口候補を整理', exact: true }).click()
    await expect(panel).toContainText('現在の候補')
    await expect(panel).toContainText('用途・送信可否は未確認')
    await assessment.locator('summary').click()
    await assessment.getByRole('combobox', { name: '窓口用途', exact: true }).selectOption('business')
    await assessment.getByRole('combobox', { name: '窓口の対象範囲', exact: true }).selectOption('company')
    await assessment.getByLabel('用途の根拠URL', { exact: true }).fill('https://approval.example/contact')
    await assessment.getByLabel('公開ページの用途説明', { exact: true }).fill('事業提携などのご相談はこちらで受け付けます。')
    await assessment.getByRole('button', { name: '用途確認を記録', exact: true }).click()
    await expect(assessment).toContainText('用途確認：CURRENT / 記録版 1')
    await expect(assessment).not.toContainText('DESTINATION_PURPOSE_UNCERTAIN')
    await expect(assessment).toContainText('EMAIL_UNVERIFIED')
    await assessment.getByRole('button', { name: '用途確認を取り消す', exact: true }).click()
    await expect(assessment).toContainText('用途確認：REVOKED / 記録版 2')
    await expect(assessment).toContainText('DESTINATION_REVIEW_REVOKED')
    await identity.getByRole('button', { name: '照合確認を取り消す', exact: true }).click()
    await expect(identity).toContainText('Human確認：REVOKED / 記録版 2')
    await expect(assessment).toContainText('IDENTITY_UNCERTAIN')
    await expect(panel.getByRole('button', { name: /送信|承認/ })).toHaveCount(0)
    expect(forbidden).toEqual([])
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  } finally {
    execFileSync(python, ['../backend/tests/e2e_user.py', 'cleanup'], { env })
  }
})
