import { execFileSync } from 'node:child_process'
import { randomBytes } from 'node:crypto'
import { test, expect } from '@playwright/test'

test('Raw Pilot is separate, Human truth is versioned, and unknown precision stays null', async ({ page }) => {
  test.setTimeout(120_000)
  const python = process.env.PYTHON || (process.platform === 'win32' ? '../backend/.venv/Scripts/python.exe' : '../backend/.venv/bin/python')
  const env = { ...process.env, E2E_EMAIL: `e2e-raw-${randomBytes(8).toString('hex')}@example.com`, E2E_PASSWORD: randomBytes(24).toString('hex') }
  execFileSync(python, ['../backend/tests/e2e_user.py', 'create'], { env })
  const forbidden: string[] = []
  page.on('request', r => { if (!['localhost', '127.0.0.1'].includes(new URL(r.url()).hostname) || /\/(send|dispatch|execute|approve|test-send|search)([/?]|$)/.test(r.url())) forbidden.push(r.url()) })
  try {
    await page.goto('/')
    await page.getByLabel('メールアドレス').fill(env.E2E_EMAIL)
    await page.getByLabel('パスワード').fill(env.E2E_PASSWORD)
    await page.getByRole('button', { name: 'ログインする', exact: true }).click()
    await page.getByRole('dialog', { name: '3ステップで始めましょう' }).getByRole('button', { name: 'あとで見る' }).click()
    await page.getByRole('button', { name: '◎ 一次収集Benchmark', exact: true }).click()
    const raw = page.getByRole('region', { name: 'Raw Collection Benchmark', exact: true })
    await raw.getByLabel('Benchmark地域', { exact: true }).fill('兵庫県姫路市')
    await raw.getByLabel('Benchmark業種', { exact: true }).fill('美容院')
    await raw.getByRole('button', { name: '空のRaw Benchmarkを作成', exact: true }).click()
    const metrics = raw.getByRole('region', { name: 'Raw Collection集計', exact: true })
    await expect(metrics).toContainText('Found 0 / Reviewed 0 / Correct 0')
    await expect(metrics).toContainText('Strict Precision 未測定 / null')
    await expect(metrics).toContainText('Coverage 未測定 / null')
    const benchmark = await raw.getByLabel('Raw Benchmark', { exact: true }).inputValue()
    const fixture = JSON.parse(execFileSync(python, ['../backend/tests/e2e_raw_benchmark.py', benchmark], { env, encoding: 'utf8' })) as { snapshot_ids: string[] }
    await raw.getByRole('button', { name: 'Raw結果を再読込', exact: true }).click()
    await expect(metrics).toContainText('Found 3 / Reviewed 0 / Correct 0')
    await expect(metrics).toContainText('Run Comparison / Marginal Gain')
    await expect(metrics).toContainText('Source Comparison')
    await metrics.getByRole('button', { name: 'この収集を中断', exact: true }).click()
    await expect(metrics).toContainText('CANCELLED')
    const first = raw.locator(`details[aria-label="Raw候補 ${fixture.snapshot_ids[0]}"]`)
    await first.locator('summary').click()
    await first.getByRole('button', { name: 'Humanレビューを開始', exact: true }).click()
    await first.getByLabel('Raw判定', { exact: true }).selectOption('CORRECT')
    await first.getByLabel('店舗照合ID', { exact: true }).fill('store-001')
    await first.getByLabel('Raw判定の理由', { exact: true }).fill('Synthetic Human truth for browser verification')
    await first.getByLabel('Raw判定の根拠URL', { exact: true }).fill('https://evidence.example/page')
    await expect(first.getByRole('button', { name: 'Rawレビューを記録', exact: true })).toBeDisabled()
    await first.getByLabel('このRaw候補の判定と根拠を自分で確認しました', { exact: true }).check()
    await page.route('**/raw-benchmarks/snapshots/*/reviews', r => r.fulfill({ status: 409, json: { detail: 'Synthetic review conflict; reload required' } }))
    await first.getByRole('button', { name: 'Rawレビューを記録', exact: true }).click()
    await expect(first.getByRole('alert')).toContainText('Synthetic review conflict')
    await expect(metrics).toContainText('Found 3 / Reviewed 0 / Correct 0')
    await page.unroute('**/raw-benchmarks/snapshots/*/reviews')
    await first.getByRole('button', { name: 'Rawレビューを記録', exact: true }).click()
    await expect(metrics).toContainText('Found 3 / Reviewed 1 / Correct 1')
    await expect(metrics).toContainText('Strict Precision 100.0%')
    const second = raw.locator(`details[aria-label="Raw候補 ${fixture.snapshot_ids[1]}"]`)
    await second.locator('summary').click()
    await second.getByRole('button', { name: 'Humanレビューを開始', exact: true }).click()
    await second.getByLabel('Raw判定', { exact: true }).selectOption('DUPLICATE')
    await second.getByLabel('重複先', { exact: true }).selectOption(fixture.snapshot_ids[0])
    await second.getByLabel('Raw判定の理由', { exact: true }).fill('Synthetic duplicate of the first reviewed entity')
    await second.getByLabel('Raw判定の根拠URL', { exact: true }).fill('https://evidence.example/page')
    await second.getByLabel('このRaw候補の判定と根拠を自分で確認しました', { exact: true }).check()
    await second.getByRole('button', { name: 'Rawレビューを記録', exact: true }).click()
    await expect(metrics).toContainText('Duplicate Rate 50.0%')
    const third = raw.locator(`details[aria-label="Raw候補 ${fixture.snapshot_ids[2]}"]`)
    await third.locator('summary').click()
    await third.getByRole('button', { name: 'Humanレビューを開始', exact: true }).click()
    await third.getByLabel('Raw判定の理由', { exact: true }).fill('Synthetic insufficient evidence; uncertain')
    await third.getByLabel('Raw判定の根拠URL', { exact: true }).fill('https://evidence.example/page')
    await third.getByLabel('このRaw候補の判定と根拠を自分で確認しました', { exact: true }).check()
    await third.getByRole('button', { name: 'Rawレビューを記録', exact: true }).click()
    await expect(metrics).toContainText('Strict Precision 33.3% / Resolved Precision 50.0%')
    await expect(metrics).toContainText('Uncertain Rate 33.3%')
    await first.locator('summary').click()
    await first.getByRole('button', { name: 'Humanレビューを開始', exact: true }).click()
    await first.getByLabel('Raw判定', { exact: true }).selectOption('WRONG_AREA')
    await first.getByLabel('Raw判定の理由', { exact: true }).fill('Synthetic correction retained as a new review version')
    await first.getByLabel('Raw判定の根拠URL', { exact: true }).fill('https://evidence.example/page')
    await first.getByLabel('このRaw候補の判定と根拠を自分で確認しました', { exact: true }).check()
    await first.getByRole('button', { name: 'Rawレビューを記録', exact: true }).click()
    await expect(metrics).toContainText('Found 3 / Reviewed 3 / Correct 0')
    await first.locator('summary').click()
    await expect(first).toContainText('Humanレビュー版 2')
    await expect(metrics).toContainText('company_name: 0 / 0 — 未測定 / null')
    await page.route('**/raw-benchmarks/*/report', r => r.fulfill({ status: 503, json: { detail: 'Synthetic read error' } }))
    await raw.getByRole('button', { name: 'Raw結果を再読込', exact: true }).click()
    await expect(raw.getByRole('alert')).toContainText('Synthetic read error')
    await expect(metrics).toHaveCount(0)
    await page.unroute('**/raw-benchmarks/*/report')
    await raw.getByRole('button', { name: 'Raw結果を再読込', exact: true }).click()
    await expect(metrics).toContainText('Found 3 / Reviewed 3 / Correct 0')
    expect(forbidden).toEqual([])
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  } finally { execFileSync(python, ['../backend/tests/e2e_user.py', 'cleanup'], { env }) }
})
