import { test, expect } from '@playwright/test'

test('login, profile editing, project CRUD, reload and logout', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByLabel('メールアドレス').fill(process.env.E2E_EMAIL!)
  await page.getByLabel('パスワード').fill('incorrect-password')
  await page.getByRole('button', { name: 'ログインする', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('正しくありません')
  await page.getByLabel('パスワード').fill(process.env.E2E_PASSWORD!)
  await page.getByRole('button', { name: 'ログインする', exact: true }).click()
  const guide = page.getByRole('dialog', { name: '3ステップで始めましょう' })
  await expect(guide).toBeVisible()
  await expect(guide.getByText('プロジェクトを作る', { exact: true })).toBeVisible()
  await guide.getByRole('button', { name: 'あとで見る' }).click()
  await expect(page.getByRole('heading', { name: 'プロジェクト', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '⚙ メール設定' }).click()
  const smtpPanel = page.getByRole('region', { name: 'SMTP設定' })
  await expect(smtpPanel.getByRole('heading', { name: '受信メール・返信取込' })).toBeVisible()
  await smtpPanel.getByLabel('SMTPホスト').fill('smtp.example.com')
  await smtpPanel.getByLabel('送信元メールアドレス').fill('sender@example.com')
  await smtpPanel.getByLabel(/^パスワード/).fill('browser-test-password')
  await smtpPanel.getByRole('button', { name: 'SMTP設定を保存' }).click()
  await expect(page.getByText('SMTP設定を保存しました。パスワードは再表示されません。')).toBeVisible()
  await page.getByRole('button', { name: '◎ ターゲットプロファイル' }).click()
  await expect(page.getByRole('heading', { name: 'SNS運用事業者', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'トラック・運送事業者', exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('profiles.png'), fullPage: true })
  const name = `ブラウザ確認 ${testInfo.project.name}`
  await page.getByRole('article').filter({ hasText: 'SNS運用事業者' }).getByRole('button', { name: '複製' }).click()
  await page.getByLabel('プロファイル名', { exact: true }).fill(name)
  await page.getByLabel('スコアルール（JSON）').fill('invalid-json')
  await page.getByRole('button', { name: '保存する' }).click()
  await expect(page.getByRole('alert')).toContainText('有効なJSON')
  await page.getByLabel('スコアルール（JSON）').fill('{"weights":{"導入事例":20}}')
  await page.getByLabel('検索キーワード').fill('地域の企業\nサービス事業者')
  await page.getByRole('button', { name: '保存する' }).click()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await page.getByRole('article').filter({ has: page.getByRole('heading', { name, exact: true }) })
    .getByRole('button', { name: '編集', exact: true }).click()
  await expect(page.getByLabel('検索キーワード')).toHaveValue('地域の企業\nサービス事業者')
  await expect(page.getByLabel('スコアルール（JSON）')).toHaveValue(/導入事例/)
  await page.getByRole('button', { name: 'キャンセル' }).click()
  await page.getByRole('button', { name: '▦ プロジェクト', exact: true }).click()
  await page.getByRole('button', { name: '＋ プロジェクトを作成', exact: true }).click()
  const projectName = `新規営業プロジェクト ${testInfo.project.name}`
  await page.getByLabel('プロジェクト名', { exact: true }).fill(projectName)
  await page.getByLabel('ターゲットプロファイル', { exact: true }).selectOption({ label: name })
  await page.getByLabel('営業目的').fill('採用支援のご提案')
  await page.getByLabel('地域', { exact: true }).fill('大阪府 / 兵庫県')
  await page.getByRole('button', { name: '保存する' }).click()
  await expect(page.getByRole('heading', { name: projectName, exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('採用支援のご提案', { exact: true })).toBeVisible()
  const projectCard = page.getByRole('article').filter({
    has: page.getByRole('heading', { name: projectName, exact: true }),
  })
  await projectCard.getByRole('button', { name: 'メンバー' }).click()
  const membersPanel = page.getByRole('region', { name: 'プロジェクトメンバー' })
  await membersPanel.getByLabel('メンバーのメール').fill(process.env.E2E_MEMBER_EMAIL!)
  await membersPanel.getByLabel('権限').selectOption('viewer')
  await membersPanel.getByRole('button', { name: 'メンバーを保存' }).click()
  const memberRow = membersPanel.getByRole('article').filter({ hasText: process.env.E2E_MEMBER_EMAIL! })
  await expect(memberRow.getByText('閲覧者', { exact: true })).toBeVisible()
  await memberRow.getByRole('button', { name: '削除' }).click()
  await expect(memberRow).toHaveCount(0)
  await membersPanel.getByRole('button', { name: '閉じる' }).click()
  await projectCard.getByRole('button', { name: '編集', exact: true }).click()
  await page.getByLabel('営業目的').fill('車両販売のご提案')
  await page.getByLabel('ステータス').selectOption('active')
  await page.getByRole('button', { name: '保存する' }).click()
  await expect(page.getByText('車両販売のご提案', { exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('projects.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await projectCard.getByRole('button', { name: '企業収集', exact: true }).click()
  await expect(page.getByRole('heading', { name: '収集条件' })).toBeVisible()
  await page.getByLabel('収集元').selectOption('url')
  await page.getByLabel('URL（1行に1件）').fill('https://example.com\nhttps://www.example.com/about\ninvalid')
  await page.getByRole('button', { name: '収集を開始' }).click()
  await expect(page.getByText('保存 1', { exact: true })).toBeVisible()
  await expect(page.getByText('重複 1', { exact: true })).toBeVisible()
  await expect(page.getByText('エラー 1', { exact: true })).toBeVisible()
  await expect(page.getByRole('strong').filter({ hasText: /^example\.com$/ })).toBeVisible()
  await page.getByLabel('URL（1行に1件）').fill('https://instagram.com/example-company')
  await page.getByRole('button', { name: '収集を開始' }).click()
  await expect(page.getByText('公式外 1', { exact: true })).toBeVisible()
  await page.getByLabel('収集元').selectOption('csv')
  await page.getByLabel('CSVファイル（UTF-8・最大5MB・1000行）').setInputFiles({
    name: 'companies.csv', mimeType: 'text/csv',
    buffer: Buffer.from('会社名,Webサイト,電話番号,メールアドレス,所在地\nCSV確認会社,https://csv.example,03-0000-0000,,東京都'),
  })
  await expect(page.getByText('1行を検出しました。', { exact: false })).toBeVisible()
  await expect(page.getByLabel('会社名')).toHaveValue('会社名')
  await page.getByRole('button', { name: '収集を開始' }).click()
  await expect(page.getByText('収集処理が完了しました。結果を確認してください。')).toBeVisible()
  await expect(page.getByRole('article').filter({ hasText: 'CSV確認会社' })).toBeVisible()
  await page.getByLabel('収集元').selectOption('serper')
  await page.getByLabel('検索キーワード（1行に1件）').fill('APIキー未設定の確認')
  await page.getByRole('button', { name: '収集を開始' }).click()
  await expect(page.getByText('検索収集をバックグラウンド処理へ登録しました。')).toBeVisible()
  const searchOperation = page.getByRole('article').filter({ hasText: '検索収集' }).first()
  await expect(searchOperation.getByText('待機中', { exact: true })).toBeVisible()
  await searchOperation.getByRole('button', { name: 'キャンセル' }).click()
  await expect(searchOperation.getByText('キャンセル', { exact: true })).toBeVisible()
  await page.getByLabel('テンプレート名').fill('大阪の定期検索')
  await page.getByLabel('実行間隔（時間）').fill('24')
  await page.getByLabel('プロジェクト企業上限').fill('500')
  await page.getByRole('button', { name: '現在の検索条件を保存' }).click()
  const scheduleCard = page.getByRole('article').filter({ hasText: '大阪の定期検索' })
  await expect(scheduleCard.getByText('24時間ごと', { exact: false })).toBeVisible()
  const analyticsRow = page.getByRole('row').filter({ hasText: '大阪の定期検索' })
  await expect(analyticsRow).toContainText('0%')
  await scheduleCard.getByRole('button', { name: '今すぐ実行' }).click()
  const scheduledOperation = page.getByRole('article').filter({ hasText: '検索収集' }).first()
  await expect(scheduledOperation.getByText('待機中', { exact: true })).toBeVisible()
  await scheduledOperation.getByRole('button', { name: 'キャンセル' }).click()
  await scheduleCard.getByRole('button', { name: '削除' }).click()
  await expect(scheduleCard).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('collection.png'), fullPage: true })
  await page.getByRole('button', { name: '▤ 企業一覧' }).click()
  await expect(page.getByRole('heading', { name: '企業一覧', exact: true, level: 1 })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'データ品質' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '重複候補' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '保存フィルター' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '担当者別営業成果' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '営業アプローチキュー' })).toBeVisible()
  const refreshPanel = page.getByRole('heading', { name: '自動再解析' }).locator('xpath=ancestor::section[1]')
  await refreshPanel.getByLabel('実行間隔（時間）').fill('24')
  await refreshPanel.getByLabel('期限切れ判定（日）').fill('30')
  await refreshPanel.getByLabel('1回の最大件数').fill('20')
  await refreshPanel.getByRole('button', { name: '自動再解析を設定' }).click()
  await expect(page.getByText('自動再解析設定を保存しました。')).toBeVisible()
  await expect(refreshPanel.getByText('有効', { exact: true })).toBeVisible()
  await refreshPanel.getByRole('button', { name: '停止' }).click()
  await expect(refreshPanel.getByText('停止中', { exact: true })).toBeVisible()
  await page.getByLabel('フィルター名').fill('確認用フィルター')
  await page.getByRole('button', { name: '現在の条件を保存' }).click()
  const savedFilter = page.getByRole('article').filter({ hasText: '確認用フィルター' })
  await expect(savedFilter).toBeVisible()
  await savedFilter.getByRole('button', { name: '適用' }).click()
  await savedFilter.getByRole('button', { name: '現在の条件で上書き' }).click()
  await expect(page.getByText('保存フィルターを現在の条件で上書きしました。')).toBeVisible()
  await savedFilter.getByRole('button', { name: '名前変更' }).click()
  await page.getByLabel('確認用フィルターの保存名').fill('名称変更済み')
  await page.getByRole('button', { name: '名前を保存' }).click()
  const renamedFilter = page.getByRole('article').filter({ hasText: '名称変更済み' })
  await expect(renamedFilter).toBeVisible()
  await renamedFilter.getByRole('button', { name: '削除' }).click()
  await expect(renamedFilter).toHaveCount(0)
  await expect(page.getByText('連絡先なし', { exact: true })).toBeVisible()
  const companyRow = page.getByRole('row').filter({ hasText: 'example.com' }).filter({
    has: page.getByRole('button', { name: '詳細' }),
  })
  await companyRow.getByRole('button', { name: '詳細' }).click()
  const detail = page.getByRole('region', { name: '企業詳細' })
  await expect(detail.getByRole('heading', { name: 'example.com' })).toBeVisible()
  await expect(detail.getByRole('heading', { name: 'Web解析ページ' })).toBeVisible()
  await detail.getByRole('textbox', { name: '電話', exact: true }).fill('03-1234-5678')
  await detail.getByLabel('電話をWeb再解析から保護').check()
  await detail.getByLabel('担当者').fill('佐藤')
  await detail.getByRole('button', { name: '企業情報を保存' }).click()
  await expect(page.getByText('企業情報を保存しました。')).toBeVisible()
  await expect(detail.getByLabel('電話をWeb再解析から保護')).toBeChecked()
  await detail.getByLabel('確認状態').selectOption('verified')
  await detail.getByLabel('この企業への連絡を禁止').check()
  await detail.getByLabel('除外理由').fill('ブラウザ確認用の連絡拒否')
  await detail.getByRole('button', { name: '連絡制御を保存' }).click()
  await expect(page.getByText('連絡制御と連絡先品質を保存しました。')).toBeVisible()
  await detail.getByLabel('この企業への連絡を禁止').uncheck()
  await detail.getByLabel('除外理由').fill('')
  await detail.getByRole('button', { name: '連絡制御を保存' }).click()
  await detail.getByLabel('営業状況').selectOption('target')
  await detail.getByLabel('メモ').fill('ブラウザテストから営業対象に更新')
  await detail.getByLabel('次回対応日時').fill('2026-09-30T10:00')
  await detail.getByRole('button', { name: '営業状況を保存' }).click()
  await expect(page.getByText('営業状況を保存しました。')).toBeVisible()
  await detail.getByRole('button', { name: '閉じる' }).click()
  const outreachPanel = page.getByRole('heading', { name: '営業アプローチキュー' }).locator('xpath=ancestor::section[1]')
  const outreachRow = outreachPanel.getByRole('row').filter({ hasText: 'example.com' })
  await outreachRow.getByRole('button', { name: '対応する' }).click()
  await outreachPanel.getByLabel('連絡経路').selectOption('call')
  await outreachPanel.getByLabel('結果').selectOption('approached')
  await outreachPanel.getByLabel('対応内容').fill('担当者へ電話してサービス概要を案内')
  await outreachPanel.getByRole('button', { name: '対応を記録' }).click()
  await expect(page.getByText('アプローチと次回対応を記録しました。')).toBeVisible()
  await companyRow.getByRole('button', { name: '詳細' }).click()
  const contactsPanel = page.getByRole('region', { name: '先方担当者' })
  await contactsPanel.getByLabel('担当者氏名').fill('山田 花子')
  await contactsPanel.getByLabel('部署').fill('営業部')
  await contactsPanel.getByLabel('役職').fill('部長')
  await contactsPanel.getByLabel('担当者メール').fill('hanako@example.com')
  await contactsPanel.getByLabel('確認状態').selectOption('verified')
  await contactsPanel.getByRole('button', { name: '担当者を追加' }).click()
  await expect(page.getByText('先方担当者を追加しました。')).toBeVisible()
  const contactCard = contactsPanel.getByRole('article').filter({ hasText: '山田 花子' })
  await expect(contactCard.getByText('確認済み')).toBeVisible()
  await contactCard.getByRole('button', { name: '編集' }).click()
  await contactsPanel.getByLabel('役職').fill('営業本部長')
  await contactsPanel.getByRole('button', { name: '担当者情報を更新' }).click()
  await expect(contactCard.getByText('営業本部長')).toBeVisible()
  const draftsPanel = page.getByRole('region', { name: '営業文面' })
  await expect(draftsPanel.getByRole('heading', { name: '営業文面' })).toBeVisible()
  await expect(draftsPanel.getByRole('button', { name: '文面を生成' })).toBeDisabled()
  await page.getByLabel('活動種別').selectOption('call')
  await page.getByLabel('活動内容').fill('担当者へ電話、次回対応日を設定')
  await page.getByRole('button', { name: '履歴を追加' }).click()
  await expect(page.getByText('活動履歴を追加しました。')).toBeVisible()
  await expect(page.getByText('担当者へ電話、次回対応日を設定')).toBeVisible()
  await detail.getByLabel('次回対応日時').fill('2026-09-19T10:00')
  await detail.getByRole('button', { name: '営業状況を保存' }).click()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'CSV出力' }).click()
  await downloadPromise
  await page.screenshot({ path: testInfo.outputPath('companies.png'), fullPage: true })
  await page.getByRole('button', { name: '⌂ ダッシュボード' }).click()
  await expect(page.getByRole('heading', { name: 'ダッシュボード' })).toBeVisible()
  await expect(page.getByText('アプローチ済', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: '営業活動成果' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '送信方法・文面別の成果' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '通知' })).toBeVisible()
  await page.getByRole('button', { name: '✉ メール配信状況' }).click()
  await expect(page.locator('h1', { hasText: 'メール配信状況' })).toBeVisible()
  await expect(page.getByLabel('メール配信状況')).toBeVisible()
  await page.getByRole('button', { name: '⌂ ダッシュボード' }).click()
  const notification = page.getByRole('article').filter({ hasText: 'フォロー期限超過: example.com' })
  await expect(notification.getByText('未読', { exact: true })).toBeVisible()
  await notification.getByRole('button', { name: '既読にする' }).click()
  await expect(notification.getByText('既読', { exact: true })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: '返信率' })).toBeVisible()
  await page.getByLabel('集計期間').selectOption('90')
  await page.screenshot({ path: testInfo.outputPath('dashboard.png'), fullPage: true })
  await page.getByRole('button', { name: '▦ プロジェクト', exact: true }).click()
  page.on('dialog', dialog => dialog.accept())
  await projectCard.getByRole('button', { name: '削除', exact: true }).click()
  await expect(page.getByRole('heading', { name: projectName, exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '◎ ターゲットプロファイル' }).click()
  await page.getByRole('article').filter({ has: page.getByRole('heading', { name, exact: true }) })
    .getByRole('button', { name: '削除', exact: true }).click()
  await expect(page.getByRole('heading', { name, exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '＋ プロファイルを作成' }).click()
  await page.getByLabel('プロファイル名', { exact: true }).fill('新しい業種')
  await page.getByRole('button', { name: '保存する' }).click()
  await expect(page.getByRole('heading', { name: '新しい業種', exact: true })).toBeVisible()
  await page.getByRole('article').filter({ hasText: '新しい業種' }).getByRole('button', { name: '削除' }).click()
  await expect(page.getByRole('heading', { name: '新しい業種', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'ログアウト', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'ログイン', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'ログイン', exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('login.png'), fullPage: true })
  expect(errors).toEqual([])
})
