import { test, expect } from '@playwright/test'

test('login, profile editing, project CRUD, reload and logout', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByLabel('メールアドレス').fill(process.env.E2E_EMAIL!)
  await page.getByLabel('パスワード').fill('incorrect-password')
  await page.getByRole('button', { name: 'ログインする', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('正しくありません')
  await page.getByLabel('パスワード').fill(process.env.E2E_PASSWORD!)
  await page.getByRole('button', { name: 'ログインする', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'プロジェクト', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '◎ ターゲットプロファイル' }).click()
  await expect(page.getByRole('heading', { name: 'SNS運用事業者', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'トラック・運送事業者', exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('profiles.png'), fullPage: true })
  const name = `ブラウザ確認 ${testInfo.project.name}`
  await page.getByRole('article').filter({ hasText: 'SNS運用事業者' }).getByRole('button', { name: '複製' }).click()
  await page.getByLabel('プロファイル名', { exact: true }).fill(name)
  await page.getByLabel('スコアルール（JSON）').fill('invalid-json')
  await page.getByRole('button', { name: '保存する' }).click()
  await expect(page.getByRole('alert')).toContainText('有効なJSON')
  await page.getByLabel('スコアルール（JSON）').fill('{"weights":{"導入事例":20}}')
  await page.getByLabel('検索キーワード').fill('地域の企業\nサービス事業者')
  await page.getByRole('button', { name: '保存する' }).click()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await page.getByRole('article').filter({ has: page.getByRole('heading', { name, exact: true }) })
    .getByRole('button', { name: '編集', exact: true }).click()
  await expect(page.getByLabel('検索キーワード')).toHaveValue('地域の企業\nサービス事業者')
  await expect(page.getByLabel('スコアルール（JSON）')).toHaveValue(/導入事例/)
  await page.getByRole('button', { name: 'キャンセル' }).click()
  await page.getByRole('button', { name: '▦ プロジェクト', exact: true }).click()
  await page.getByRole('button', { name: '＋ プロジェクトを作成', exact: true }).click()
  await page.getByLabel('プロジェクト名', { exact: true }).fill('新規営業プロジェクト')
  await page.getByLabel('ターゲットプロファイル', { exact: true }).selectOption({ label: name })
  await page.getByLabel('営業目的').fill('採用支援のご提案')
  await page.getByLabel('地域', { exact: true }).fill('大阪府 / 兵庫県')
  await page.getByRole('button', { name: '保存する' }).click()
  await expect(page.getByRole('heading', { name: '新規営業プロジェクト', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('採用支援のご提案', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '編集', exact: true }).click()
  await page.getByLabel('営業目的').fill('車両販売のご提案')
  await page.getByLabel('ステータス').selectOption('active')
  await page.getByRole('button', { name: '保存する' }).click()
  await expect(page.getByText('車両販売のご提案', { exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('projects.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  page.on('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '削除', exact: true }).click()
  await expect(page.getByRole('heading', { name: '最初のプロジェクトを作成しましょう' })).toBeVisible()
  await page.getByRole('button', { name: '◎ ターゲットプロファイル' }).click()
  await page.getByRole('article').filter({ has: page.getByRole('heading', { name, exact: true }) })
    .getByRole('button', { name: '削除', exact: true }).click()
  await expect(page.getByRole('heading', { name, exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '＋ プロファイルを作成' }).click()
  await page.getByLabel('プロファイル名', { exact: true }).fill('新しい業種')
  await page.getByRole('button', { name: '保存する' }).click()
  await expect(page.getByRole('heading', { name: '新しい業種', exact: true })).toBeVisible()
  await page.getByRole('article').filter({ hasText: '新しい業種' }).getByRole('button', { name: '削除' }).click()
  await expect(page.getByRole('heading', { name: '新しい業種', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'ログアウト', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'ログイン', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'ログイン', exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('login.png'), fullPage: true })
  expect(errors).toEqual([])
})
