"""lead completion evidence and destinations"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0596f0531982"
down_revision = "0485ef420871"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact_destinations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("destination_type", sa.String(length=10), nullable=False),
        sa.Column("destination", sa.Text(), nullable=False),
        sa.Column("shared_destination_key", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("purpose", sa.String(length=30), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "destination_type IN ('email','form')", name="ck_contact_destination_type"
        ),
        sa.CheckConstraint(
            "scope IN ('company','location','group','unknown')", name="ck_contact_destination_scope"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id",
            "destination_type",
            "shared_destination_key",
            name="uq_contact_destination_project_key",
        ),
    )
    op.create_index(
        op.f("ix_contact_destinations_project_id"),
        "contact_destinations",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "lead_destination_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("destination_id", sa.Uuid(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["destination_id"], ["contact_destinations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "destination_id", name="uq_lead_destination_link"),
    )
    op.create_index(
        op.f("ix_lead_destination_links_company_id"),
        "lead_destination_links",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lead_destination_links_destination_id"),
        "lead_destination_links",
        ["destination_id"],
        unique=False,
    )
    op.create_table(
        "lead_site_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("identity_hash", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.String(length=20), nullable=False),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IN ('CONFIRMED','HIGH','MEDIUM','LOW','REVIEW_REQUIRED')",
            name="ck_lead_site_confidence",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lead_site_evidence_company_id"), "lead_site_evidence", ["company_id"], unique=False
    )
    op.create_table(
        "lead_source_observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("collection_job_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("terms_reference", sa.Text(), nullable=False),
        sa.Column("allowed_usage", sa.String(length=40), nullable=False),
        sa.Column("attribution_requirement", sa.Text(), nullable=False),
        sa.Column("observation_hash", sa.String(length=64), nullable=False),
        sa.Column("identity_status", sa.String(length=20), nullable=False),
        sa.Column("identity_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("facts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("applied_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "identity_status IN ('CONFIRMED','PROBABLE','REVIEW_REQUIRED','DIFFERENT')",
            name="ck_lead_identity_status",
        ),
        sa.ForeignKeyConstraint(["collection_job_id"], ["collection_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "collection_job_id", "company_id", "observation_hash", name="uq_lead_source_observation"
        ),
    )
    op.create_index(
        op.f("ix_lead_source_observations_collection_job_id"),
        "lead_source_observations",
        ["collection_job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lead_source_observations_company_id"),
        "lead_source_observations",
        ["company_id"],
        unique=False,
    )
    op.execute("""CREATE FUNCTION lead_completion_project_guard() RETURNS trigger AS $$
    DECLARE a uuid; b uuid;
    BEGIN
      SELECT project_id INTO a FROM companies WHERE id=NEW.company_id;
      IF TG_TABLE_NAME='lead_destination_links' THEN
        SELECT project_id INTO b FROM contact_destinations WHERE id=NEW.destination_id;
      ELSE
        SELECT project_id INTO b FROM collection_jobs WHERE id=NEW.collection_job_id;
      END IF;
      IF a IS NULL OR b IS NULL OR a<>b THEN
        RAISE EXCEPTION 'Lead completion project mismatch' USING ERRCODE='23514';
      END IF;
      RETURN NEW;
    END; $$ LANGUAGE plpgsql""")
    for table in ("lead_source_observations", "lead_destination_links"):
        op.execute(
            "CREATE TRIGGER lead_completion_project_guard BEFORE INSERT OR UPDATE ON "
            + table
            + " FOR EACH ROW EXECUTE FUNCTION lead_completion_project_guard()"
        )
    # ### end Alembic commands ###


def downgrade():
    for table in (
        "lead_source_observations",
        "lead_site_evidence",
        "contact_destinations",
        "lead_destination_links",
    ):
        if op.get_bind().execute(sa.text("SELECT EXISTS (SELECT 1 FROM " + table + ")")).scalar():
            raise RuntimeError("Lead completion evidence exists; downgrade refused")
    op.execute("DROP FUNCTION lead_completion_project_guard() CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_lead_source_observations_company_id"), table_name="lead_source_observations"
    )
    op.drop_index(
        op.f("ix_lead_source_observations_collection_job_id"), table_name="lead_source_observations"
    )
    op.drop_table("lead_source_observations")
    op.drop_index(op.f("ix_lead_site_evidence_company_id"), table_name="lead_site_evidence")
    op.drop_table("lead_site_evidence")
    op.drop_index(
        op.f("ix_lead_destination_links_destination_id"), table_name="lead_destination_links"
    )
    op.drop_index(op.f("ix_lead_destination_links_company_id"), table_name="lead_destination_links")
    op.drop_table("lead_destination_links")
    op.drop_index(op.f("ix_contact_destinations_project_id"), table_name="contact_destinations")
    op.drop_table("contact_destinations")
    # ### end Alembic commands ###
