"""lead completion cohort usage and review measurements"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "06a2f819c310"
down_revision = "0596f0531982"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lead_completion_cohorts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("company_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cohort_hash", sa.String(length=64), nullable=False),
        sa.Column("context_hash", sa.String(length=64), nullable=False),
        sa.Column("definition_version", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lead_completion_cohorts_project_id"),
        "lead_completion_cohorts",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "lead_review_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cohort_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("identity_hash", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("outcome", sa.String(length=20), nullable=True),
        sa.CheckConstraint(
            "outcome IS NULL OR outcome IN "
            "('CHECKED','REVIEW','HOLD','BLOCKED','STALE','ABANDONED')",
            name="ck_lead_review_outcome",
        ),
        sa.CheckConstraint(
            "duration_seconds IS NULL OR duration_seconds BETWEEN 0 AND 14400",
            name="ck_lead_review_duration",
        ),
        sa.CheckConstraint(
            "finished_at IS NULL OR finished_at >= started_at", name="ck_lead_review_time"
        ),
        sa.ForeignKeyConstraint(["cohort_id"], ["lead_completion_cohorts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lead_review_sessions_cohort_id"),
        "lead_review_sessions",
        ["cohort_id"],
        unique=False,
    )
    op.create_index(
        "uq_lead_review_active",
        "lead_review_sessions",
        ["cohort_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("finished_at IS NULL"),
    )
    op.create_table(
        "lead_processing_usage",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("collection_job_id", sa.Uuid(), nullable=True),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("elapsed_ms", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("estimated_cost", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("pricing_version", sa.String(length=100), nullable=True),
        sa.CheckConstraint("kind IN ('search','ai')", name="ck_lead_usage_kind"),
        sa.CheckConstraint("status IN ('completed','failed')", name="ck_lead_usage_status"),
        sa.CheckConstraint("elapsed_ms >= 0", name="ck_lead_usage_elapsed"),
        sa.CheckConstraint(
            "estimated_cost IS NULL OR estimated_cost >= 0", name="ck_lead_usage_cost"
        ),
        sa.CheckConstraint("input_tokens IS NULL OR input_tokens >= 0", name="ck_lead_usage_input"),
        sa.CheckConstraint(
            "output_tokens IS NULL OR output_tokens >= 0", name="ck_lead_usage_output"
        ),
        sa.ForeignKeyConstraint(["collection_job_id"], ["collection_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lead_processing_usage_collection_job_id"),
        "lead_processing_usage",
        ["collection_job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lead_processing_usage_company_id"),
        "lead_processing_usage",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lead_processing_usage_project_id"),
        "lead_processing_usage",
        ["project_id"],
        unique=False,
    )
    op.execute("""
    CREATE FUNCTION completion_measurement_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE tenant uuid;
    BEGIN
      IF TG_TABLE_NAME = 'lead_completion_cohorts' THEN
        IF TG_OP = 'UPDATE' THEN
          RAISE EXCEPTION 'Fixed cohort cannot be changed' USING ERRCODE='23514';
        END IF;
        IF jsonb_typeof(NEW.company_ids) <> 'array'
          OR jsonb_array_length(NEW.company_ids) NOT BETWEEN 1 AND 3000
          OR (SELECT count(DISTINCT value) FROM jsonb_array_elements_text(NEW.company_ids))
            <> jsonb_array_length(NEW.company_ids)
          OR EXISTS (SELECT 1 FROM jsonb_array_elements_text(NEW.company_ids) value WHERE NOT EXISTS
            (SELECT 1 FROM companies c WHERE c.id=value::uuid AND c.project_id=NEW.project_id)) THEN
          RAISE EXCEPTION 'Invalid cohort project membership' USING ERRCODE='23514';
        END IF;
      ELSIF TG_TABLE_NAME = 'lead_review_sessions' THEN
        SELECT project_id INTO tenant FROM lead_completion_cohorts WHERE id=NEW.cohort_id;
        IF TG_OP = 'INSERT' THEN
          IF NOT EXISTS (SELECT 1 FROM companies c
            JOIN lead_completion_cohorts g ON g.id=NEW.cohort_id
            WHERE c.id=NEW.company_id AND c.project_id=tenant
              AND g.company_ids ? NEW.company_id::text) THEN
            RAISE EXCEPTION 'Invalid review project membership' USING ERRCODE='23514';
          END IF;
        ELSIF OLD.finished_at IS NOT NULL OR NEW.cohort_id<>OLD.cohort_id
          OR NEW.company_id<>OLD.company_id
          OR NEW.user_id<>OLD.user_id OR NEW.identity_hash<>OLD.identity_hash
          OR NEW.started_at<>OLD.started_at THEN
          RAISE EXCEPTION 'Review identity or terminal record cannot be changed'
            USING ERRCODE='23514';
        END IF;
      ELSE
        IF (NEW.collection_job_id IS NOT NULL AND NOT EXISTS
          (SELECT 1 FROM collection_jobs j
           WHERE j.id=NEW.collection_job_id AND j.project_id=NEW.project_id))
          OR (NEW.company_id IS NOT NULL AND NOT EXISTS
          (SELECT 1 FROM companies c
           WHERE c.id=NEW.company_id AND c.project_id=NEW.project_id)) THEN
          RAISE EXCEPTION 'Invalid usage project membership' USING ERRCODE='23514';
        END IF;
      END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER completion_cohort_guard BEFORE INSERT OR UPDATE ON lead_completion_cohorts
      FOR EACH ROW EXECUTE FUNCTION completion_measurement_guard();
    CREATE TRIGGER completion_review_guard BEFORE INSERT OR UPDATE ON lead_review_sessions
      FOR EACH ROW EXECUTE FUNCTION completion_measurement_guard();
    CREATE TRIGGER completion_usage_guard BEFORE INSERT OR UPDATE ON lead_processing_usage
      FOR EACH ROW EXECUTE FUNCTION completion_measurement_guard();
    """)
    # ### end Alembic commands ###


def downgrade():
    bind = op.get_bind()
    for table in ("lead_completion_cohorts", "lead_review_sessions", "lead_processing_usage"):
        if bind.execute(sa.text(f"SELECT EXISTS (SELECT 1 FROM {table})")).scalar():
            raise RuntimeError("Completion measurements exist; downgrade refused")
    op.execute("DROP FUNCTION completion_measurement_guard() CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lead_processing_usage_project_id"), table_name="lead_processing_usage")
    op.drop_index(op.f("ix_lead_processing_usage_company_id"), table_name="lead_processing_usage")
    op.drop_index(
        op.f("ix_lead_processing_usage_collection_job_id"), table_name="lead_processing_usage"
    )
    op.drop_table("lead_processing_usage")
    op.drop_index(
        "uq_lead_review_active",
        table_name="lead_review_sessions",
        postgresql_where=sa.text("finished_at IS NULL"),
    )
    op.drop_index(op.f("ix_lead_review_sessions_cohort_id"), table_name="lead_review_sessions")
    op.drop_table("lead_review_sessions")
    op.drop_index(
        op.f("ix_lead_completion_cohorts_project_id"), table_name="lead_completion_cohorts"
    )
    op.drop_table("lead_completion_cohorts")
    # ### end Alembic commands ###
