"""Raw collection Pilot snapshots and Human truth"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "111884efd88e"
down_revision = "37945a503231"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_benchmarks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("region", sa.String(length=500), nullable=False),
        sa.Column("industry", sa.String(length=300), nullable=False),
        sa.Column("definition_version", sa.String(length=40), nullable=False),
        sa.Column("code_commit", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id"),
    )
    op.create_table(
        "raw_query_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("benchmark_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("keyword", sa.String(length=300), nullable=False),
        sa.Column("query", sa.String(length=1000), nullable=False),
        sa.Column("requested_count", sa.Integer(), nullable=False),
        sa.Column("code_commit", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('RUNNING','COMPLETED','FAILED','CANCELLED')", name="ck_raw_run_status"
        ),
        sa.CheckConstraint("requested_count BETWEEN 1 AND 30", name="ck_raw_run_count"),
        sa.ForeignKeyConstraint(
            ["benchmark_id"],
            ["raw_benchmarks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("benchmark_id", "ordinal", name="uq_raw_run_order"),
        sa.UniqueConstraint("benchmark_id", "source", "keyword", name="uq_raw_run_query"),
    )
    op.create_index(
        op.f("ix_raw_query_runs_benchmark_id"), "raw_query_runs", ["benchmark_id"], unique=False
    )
    op.create_table(
        "raw_lead_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "collected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["raw_query_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "position", name="uq_raw_snapshot_position"),
    )
    op.create_index(
        op.f("ix_raw_lead_snapshots_run_id"), "raw_lead_snapshots", ["run_id"], unique=False
    )
    op.create_table(
        "raw_review_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["raw_lead_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_raw_review_sessions_snapshot_id"),
        "raw_review_sessions",
        ["snapshot_id"],
        unique=False,
    )
    op.create_table(
        "raw_lead_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("outcome", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("evidence_url", sa.Text(), nullable=False),
        sa.Column("entity_key", sa.String(length=100), nullable=False),
        sa.Column("duplicate_of", sa.Uuid(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "outcome IN ('CORRECT','WRONG_INDUSTRY','WRONG_AREA','DUPLICATE','WRONG_ENTITY',"
            "'PORTAL_OR_AGGREGATOR','CLOSED_OR_INACTIVE','UNCERTAIN','OTHER')",
            name="ck_raw_review_outcome",
        ),
        sa.CheckConstraint("duration_seconds BETWEEN 0 AND 14400", name="ck_raw_review_duration"),
        sa.CheckConstraint("version > 0", name="ck_raw_review_version"),
        sa.ForeignKeyConstraint(
            ["duplicate_of"],
            ["raw_lead_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["raw_review_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["raw_lead_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", name="uq_raw_review_session"),
        sa.UniqueConstraint("snapshot_id", "version", name="uq_raw_review_version"),
    )
    op.create_index(
        op.f("ix_raw_lead_reviews_snapshot_id"), "raw_lead_reviews", ["snapshot_id"], unique=False
    )
    # ### end Alembic commands ###

    op.execute("""
    CREATE FUNCTION raw_collection_immutable_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION 'Raw evidence is immutable; use an appended Human review'
        USING ERRCODE='23514';
    END $$;
    CREATE FUNCTION raw_review_insert_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE last_version integer;
    BEGIN
      PERFORM 1 FROM raw_lead_snapshots WHERE id=NEW.snapshot_id FOR UPDATE;
      IF NOT EXISTS (
        SELECT 1 FROM raw_lead_snapshots s JOIN raw_query_runs q ON q.id=s.run_id
        JOIN raw_benchmarks b ON b.id=q.benchmark_id JOIN projects p ON p.id=b.project_id
        JOIN raw_review_sessions t ON t.id=NEW.session_id
        WHERE s.id=NEW.snapshot_id AND s.snapshot_hash=NEW.snapshot_hash
          AND t.snapshot_id=s.id AND t.user_id=NEW.reviewer_id
          AND t.snapshot_hash=s.snapshot_hash AND NEW.reviewed_at >= t.started_at
          AND NEW.reviewed_at <= t.started_at + interval '4 hours'
          AND (p.user_id=NEW.reviewer_id OR EXISTS (
            SELECT 1 FROM project_members m WHERE m.project_id=p.id
              AND m.user_id=NEW.reviewer_id AND m.role='editor'))
      ) THEN RAISE EXCEPTION 'Invalid Human review boundary' USING ERRCODE='23514'; END IF;
      SELECT COALESCE(MAX(version),0) INTO last_version FROM raw_lead_reviews
        WHERE snapshot_id=NEW.snapshot_id;
      IF NEW.version<>last_version+1 THEN
        RAISE EXCEPTION 'Review version conflict' USING ERRCODE='23514';
      END IF;
      RETURN NEW;
    END $$;
    CREATE FUNCTION raw_query_definition_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF (NEW.benchmark_id,NEW.ordinal,NEW.source,NEW.keyword,NEW.query,
          NEW.requested_count,NEW.code_commit,NEW.created_at) IS DISTINCT FROM
         (OLD.benchmark_id,OLD.ordinal,OLD.source,OLD.keyword,OLD.query,
          OLD.requested_count,OLD.code_commit,OLD.created_at) THEN
        RAISE EXCEPTION 'Raw query definition is immutable' USING ERRCODE='23514';
      END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER raw_query_definition BEFORE UPDATE ON raw_query_runs
      FOR EACH ROW EXECUTE FUNCTION raw_query_definition_guard();
    CREATE TRIGGER raw_review_insert BEFORE INSERT ON raw_lead_reviews
      FOR EACH ROW EXECUTE FUNCTION raw_review_insert_guard();
    """)
    for table in ("raw_benchmarks", "raw_lead_snapshots", "raw_lead_reviews"):
        op.execute(
            f"CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION raw_collection_immutable_guard()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION raw_collection_immutable_guard()"
        )


def downgrade():
    if op.get_bind().execute(sa.text("SELECT EXISTS(SELECT 1 FROM raw_benchmarks)")).scalar():
        raise RuntimeError(
            "Raw Benchmark evidence exists; archive and plan retention before downgrade"
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_raw_lead_reviews_snapshot_id"), table_name="raw_lead_reviews")
    op.drop_table("raw_lead_reviews")
    op.drop_index(op.f("ix_raw_review_sessions_snapshot_id"), table_name="raw_review_sessions")
    op.drop_table("raw_review_sessions")
    op.drop_index(op.f("ix_raw_lead_snapshots_run_id"), table_name="raw_lead_snapshots")
    op.drop_table("raw_lead_snapshots")
    op.drop_index(op.f("ix_raw_query_runs_benchmark_id"), table_name="raw_query_runs")
    op.drop_table("raw_query_runs")
    op.drop_table("raw_benchmarks")
    op.execute("DROP FUNCTION raw_review_insert_guard()")
    op.execute("DROP FUNCTION raw_query_definition_guard()")
    op.execute("DROP FUNCTION raw_collection_immutable_guard()")
    # ### end Alembic commands ###
