"""link collection jobs to search schedules"""

import sqlalchemy as sa
from alembic import op

revision = "11d84c5dfff0"
down_revision = "840baf8a6ff1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("collection_jobs", sa.Column("operation_job_id", sa.Uuid(), nullable=True))
    op.add_column("collection_jobs", sa.Column("search_schedule_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_collection_jobs_operation_job_id"),
        "collection_jobs",
        ["operation_job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collection_jobs_search_schedule_id"),
        "collection_jobs",
        ["search_schedule_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_collection_jobs_operation_job_id",
        "collection_jobs",
        "operation_jobs",
        ["operation_job_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_collection_jobs_search_schedule_id",
        "collection_jobs",
        "search_schedules",
        ["search_schedule_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_collection_jobs_search_schedule_id", "collection_jobs", type_="foreignkey"
    )
    op.drop_constraint("fk_collection_jobs_operation_job_id", "collection_jobs", type_="foreignkey")
    op.drop_index(op.f("ix_collection_jobs_search_schedule_id"), table_name="collection_jobs")
    op.drop_index(op.f("ix_collection_jobs_operation_job_id"), table_name="collection_jobs")
    op.drop_column("collection_jobs", "search_schedule_id")
    op.drop_column("collection_jobs", "operation_job_id")
    # ### end Alembic commands ###
