"""collection_fact_human_reviews"""

import sqlalchemy as sa
from alembic import context, op

revision = "1372277c354d"
down_revision = "62a91de74b20"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection_fact_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("condition_type", sa.String(length=20), nullable=False),
        sa.Column("value", sa.String(length=300), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("company_hash", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("evidence_excerpt", sa.String(length=1000), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("condition_type IN ('AREA','INDUSTRY')", name="ck_fact_review_type"),
        sa.CheckConstraint(
            "outcome IN ('MATCH','NO_MATCH','UNKNOWN')", name="ck_fact_review_outcome"
        ),
        sa.CheckConstraint("version > 0", name="ck_fact_review_version"),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id", "condition_type", "value", "version", name="uq_fact_review_version"
        ),
    )
    op.create_index(
        op.f("ix_collection_fact_reviews_company_id"),
        "collection_fact_reviews",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collection_fact_reviews_project_id"),
        "collection_fact_reviews",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    count = op.get_bind().scalar(sa.text("SELECT count(*) FROM collection_fact_reviews"))
    if (
        count
        and context.get_x_argument(as_dictionary=True).get("allow_fact_review_data_loss") != "true"
    ):
        raise RuntimeError(
            "Export fact reviews before downgrade; allow_fact_review_data_loss=true required"
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_collection_fact_reviews_project_id"), table_name="collection_fact_reviews"
    )
    op.drop_index(
        op.f("ix_collection_fact_reviews_company_id"), table_name="collection_fact_reviews"
    )
    op.drop_table("collection_fact_reviews")
    # ### end Alembic commands ###
