"""Human official site identity evidence"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "15fcce21f276"
down_revision = "e49867e60dcd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site_identity_review_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=20), nullable=False),
        sa.Column("identity_hash", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("observed_name", sa.String(length=300), nullable=False),
        sa.Column("observed_address", sa.String(length=1000), nullable=False),
        sa.Column("observed_phone", sa.String(length=100), nullable=False),
        sa.Column("evidence_excerpt", sa.String(length=1000), nullable=False),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('CONFIRMED','REVOKED')", name="ck_site_identity_review_event"
        ),
        sa.CheckConstraint(
            "expires_at > created_at AND expires_at <= created_at + interval '7 days'",
            name="ck_site_identity_review_expiry",
        ),
        sa.CheckConstraint("version > 0", name="ck_site_identity_review_version"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "version", name="uq_site_identity_review_version"),
    )
    op.create_index(
        op.f("ix_site_identity_review_events_company_id"),
        "site_identity_review_events",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_site_identity_review_events_project_id"),
        "site_identity_review_events",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    op.execute("""
    CREATE FUNCTION site_identity_review_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE last_version integer;
    BEGIN
      IF TG_OP = 'TRUNCATE' THEN
        RAISE EXCEPTION 'Identity evidence is append only' USING ERRCODE='23514';
      ELSIF TG_OP = 'DELETE' THEN
        IF NOT EXISTS (SELECT 1 FROM projects WHERE id=OLD.project_id) THEN RETURN OLD; END IF;
        RAISE EXCEPTION 'Identity evidence is append only' USING ERRCODE='23514';
      ELSIF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION 'Identity evidence is append only' USING ERRCODE='23514';
      END IF;
      PERFORM 1 FROM projects WHERE id=NEW.project_id FOR UPDATE;
      IF NOT EXISTS (SELECT 1 FROM companies c
        JOIN projects p ON p.id=c.project_id JOIN users u ON u.id=NEW.actor_user_id
        WHERE c.id=NEW.company_id AND c.project_id=NEW.project_id
          AND (p.user_id=u.id OR EXISTS (SELECT 1 FROM project_members m
             WHERE m.project_id=p.id AND m.user_id=u.id AND m.role='editor'))) THEN
        RAISE EXCEPTION 'Invalid identity project or Human membership' USING ERRCODE='23514';
      END IF;
      SELECT COALESCE(MAX(version),0) INTO last_version FROM site_identity_review_events
        WHERE company_id=NEW.company_id;
      IF NEW.version <> last_version+1 THEN
        RAISE EXCEPTION 'Identity version conflict' USING ERRCODE='23514';
      END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER site_identity_review_append_guard BEFORE INSERT OR UPDATE OR DELETE
      ON site_identity_review_events FOR EACH ROW EXECUTE FUNCTION site_identity_review_guard();
    CREATE TRIGGER site_identity_review_truncate_guard BEFORE TRUNCATE
      ON site_identity_review_events FOR EACH STATEMENT
      EXECUTE FUNCTION site_identity_review_guard();
    """)


def downgrade():
    if (
        op.get_bind()
        .execute(sa.text("SELECT EXISTS(SELECT 1 FROM site_identity_review_events)"))
        .scalar()
    ):
        raise RuntimeError("Identity evidence exists; downgrade refused")
    op.execute(
        "DROP TRIGGER IF EXISTS site_identity_review_append_guard ON site_identity_review_events"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS site_identity_review_truncate_guard ON site_identity_review_events"
    )
    op.execute("DROP FUNCTION IF EXISTS site_identity_review_guard()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_site_identity_review_events_project_id"), table_name="site_identity_review_events"
    )
    op.drop_index(
        op.f("ix_site_identity_review_events_company_id"), table_name="site_identity_review_events"
    )
    op.drop_table("site_identity_review_events")
    # ### end Alembic commands ###
