"""Human preparation destination choice"""

import sqlalchemy as sa
from alembic import op

revision = "1ea563b6ad2d"
down_revision = "15fcce21f276"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "destination_choice_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("destination_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=20), nullable=False),
        sa.Column("destination_type", sa.String(length=10), nullable=False),
        sa.Column("destination", sa.Text(), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("purpose_review_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('SELECTED','REVOKED')", name="ck_destination_choice_event"
        ),
        sa.CheckConstraint(
            "expires_at > created_at AND expires_at <= created_at + interval '7 days'",
            name="ck_destination_choice_expiry",
        ),
        sa.CheckConstraint(
            "version > 0 AND purpose_review_version > 0", name="ck_destination_choice_version"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "version", name="uq_destination_choice_version"),
    )
    op.create_index(
        op.f("ix_destination_choice_events_company_id"),
        "destination_choice_events",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_destination_choice_events_project_id"),
        "destination_choice_events",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    op.execute("""
    CREATE FUNCTION destination_choice_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE last_version integer; purpose_row record; previous_row record;
    BEGIN
      IF TG_OP = 'DELETE' THEN
        IF NOT EXISTS (SELECT 1 FROM projects WHERE id=OLD.project_id) THEN RETURN OLD; END IF;
        RAISE EXCEPTION 'Destination choice is append only' USING ERRCODE='23514';
      ELSIF TG_OP IN ('UPDATE','TRUNCATE') THEN
        RAISE EXCEPTION 'Destination choice is append only' USING ERRCODE='23514';
      END IF;
      PERFORM 1 FROM projects WHERE id=NEW.project_id FOR UPDATE;
      IF NOT EXISTS (SELECT 1 FROM companies c JOIN projects p ON p.id=c.project_id
        JOIN users u ON u.id=NEW.actor_user_id
        WHERE c.id=NEW.company_id AND c.project_id=NEW.project_id
          AND (p.user_id=u.id OR EXISTS (SELECT 1 FROM project_members m
            WHERE m.project_id=p.id AND m.user_id=u.id AND m.role='editor'))) THEN
        RAISE EXCEPTION 'Invalid choice project or Human membership' USING ERRCODE='23514';
      END IF;
      SELECT COALESCE(MAX(version),0) INTO last_version FROM destination_choice_events
        WHERE company_id=NEW.company_id;
      IF NEW.version <> last_version+1 THEN
        RAISE EXCEPTION 'Choice version conflict' USING ERRCODE='23514';
      END IF;
      IF NEW.event_type = 'SELECTED' THEN
        IF NOT EXISTS (SELECT 1 FROM contact_destinations d JOIN lead_destination_links l
          ON l.destination_id=d.id WHERE l.company_id=NEW.company_id
          AND d.id=NEW.destination_id AND d.project_id=NEW.project_id AND d.active
          AND d.destination_type=NEW.destination_type AND d.destination=NEW.destination) THEN
          RAISE EXCEPTION 'Invalid choice destination' USING ERRCODE='23514';
        END IF;
        SELECT * INTO purpose_row FROM destination_review_events
          WHERE company_id=NEW.company_id AND destination_id=NEW.destination_id
          ORDER BY version DESC LIMIT 1;
        IF purpose_row IS NULL OR purpose_row.event_type <> 'CONFIRMED'
          OR purpose_row.version <> NEW.purpose_review_version
          OR purpose_row.snapshot_hash <> NEW.snapshot_hash
          OR purpose_row.expires_at <= now() OR NEW.expires_at > purpose_row.expires_at THEN
          RAISE EXCEPTION 'Invalid choice purpose review' USING ERRCODE='23514';
        END IF;
      ELSE
        SELECT * INTO previous_row FROM destination_choice_events
          WHERE company_id=NEW.company_id ORDER BY version DESC LIMIT 1;
        IF previous_row IS NULL OR previous_row.event_type <> 'SELECTED'
          OR NEW.destination_id <> previous_row.destination_id
          OR NEW.snapshot_hash <> previous_row.snapshot_hash
          OR NEW.purpose_review_version <> previous_row.purpose_review_version
          OR NEW.destination_type <> previous_row.destination_type
          OR NEW.destination <> previous_row.destination THEN
          RAISE EXCEPTION 'Invalid choice revocation' USING ERRCODE='23514';
        END IF;
      END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER destination_choice_append_guard BEFORE INSERT OR UPDATE OR DELETE
      ON destination_choice_events FOR EACH ROW EXECUTE FUNCTION destination_choice_guard();
    CREATE TRIGGER destination_choice_truncate_guard BEFORE TRUNCATE
      ON destination_choice_events FOR EACH STATEMENT EXECUTE FUNCTION destination_choice_guard();
    """)


def downgrade():
    if (
        op.get_bind()
        .execute(sa.text("SELECT EXISTS(SELECT 1 FROM destination_choice_events)"))
        .scalar()
    ):
        raise RuntimeError("Destination choice evidence exists; downgrade refused")
    op.execute("DROP TRIGGER destination_choice_append_guard ON destination_choice_events")
    op.execute("DROP TRIGGER destination_choice_truncate_guard ON destination_choice_events")
    op.execute("DROP FUNCTION destination_choice_guard()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_destination_choice_events_project_id"), table_name="destination_choice_events"
    )
    op.drop_index(
        op.f("ix_destination_choice_events_company_id"), table_name="destination_choice_events"
    )
    op.drop_table("destination_choice_events")
    # ### end Alembic commands ###
