"""raw repeat measurements and Human pair truth"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "29d351ead7ae"
down_revision = "111884efd88e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_pair_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("left_id", sa.Uuid(), nullable=False),
        sa.Column("right_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("pair_hash", sa.String(length=64), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("evidence_url", sa.Text(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("outcome IN ('SAME','DIFFERENT','UNSURE')", name="ck_raw_pair_outcome"),
        sa.CheckConstraint("duration_seconds BETWEEN 0 AND 14400", name="ck_raw_pair_duration"),
        sa.CheckConstraint("left_id < right_id", name="ck_raw_pair_order"),
        sa.CheckConstraint("version > 0", name="ck_raw_pair_version"),
        sa.ForeignKeyConstraint(
            ["left_id"],
            ["raw_lead_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["right_id"],
            ["raw_lead_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["raw_review_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("left_id", "right_id", "version", name="uq_raw_pair_version"),
        sa.UniqueConstraint("session_id", name="uq_raw_pair_session"),
    )
    op.create_index(
        op.f("ix_raw_pair_reviews_left_id"), "raw_pair_reviews", ["left_id"], unique=False
    )
    op.add_column(
        "raw_query_runs",
        sa.Column("repeat_index", sa.Integer(), server_default="1", nullable=False),
    )
    op.drop_constraint(op.f("uq_raw_run_query"), "raw_query_runs", type_="unique")
    op.create_unique_constraint(
        "uq_raw_run_repeat", "raw_query_runs", ["benchmark_id", "source", "keyword", "repeat_index"]
    )
    # ### end Alembic commands ###
    op.create_check_constraint(
        "ck_raw_run_repeat", "raw_query_runs", "repeat_index BETWEEN 1 AND 3"
    )
    op.execute("""
    CREATE OR REPLACE FUNCTION raw_query_definition_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF (NEW.benchmark_id,NEW.ordinal,NEW.source,NEW.keyword,NEW.query,
          NEW.requested_count,NEW.code_commit,NEW.created_at,NEW.repeat_index) IS DISTINCT FROM
         (OLD.benchmark_id,OLD.ordinal,OLD.source,OLD.keyword,OLD.query,
          OLD.requested_count,OLD.code_commit,OLD.created_at,OLD.repeat_index) THEN
        RAISE EXCEPTION 'Raw query definition is immutable' USING ERRCODE='23514';
      END IF;
      RETURN NEW;
    END $$;
    CREATE FUNCTION raw_label_session_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_TABLE_NAME='raw_pair_reviews' THEN
        IF EXISTS(SELECT 1 FROM raw_lead_reviews WHERE session_id=NEW.session_id) THEN
          RAISE EXCEPTION 'Human session already used' USING ERRCODE='23514'; END IF;
      ELSE
        IF EXISTS(SELECT 1 FROM raw_pair_reviews WHERE session_id=NEW.session_id) THEN
          RAISE EXCEPTION 'Human session already used' USING ERRCODE='23514'; END IF;
      END IF;
      RETURN NEW;
    END $$;
    CREATE FUNCTION raw_pair_insert_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE last_version integer;
    BEGIN
      PERFORM 1 FROM raw_lead_snapshots WHERE id=NEW.left_id FOR UPDATE;
      IF NOT EXISTS (
        SELECT 1 FROM raw_lead_snapshots a JOIN raw_query_runs qa ON qa.id=a.run_id
        JOIN raw_lead_snapshots b ON b.id=NEW.right_id
        JOIN raw_query_runs qb ON qb.id=b.run_id AND qb.benchmark_id=qa.benchmark_id
        JOIN raw_benchmarks bm ON bm.id=qa.benchmark_id JOIN projects p ON p.id=bm.project_id
        JOIN raw_review_sessions t ON t.id=NEW.session_id
        WHERE a.id=NEW.left_id AND t.snapshot_id=a.id AND t.user_id=NEW.reviewer_id
          AND t.snapshot_hash=a.snapshot_hash AND NEW.reviewed_at >= t.started_at
          AND NEW.reviewed_at <= t.started_at + interval '4 hours'
          AND (p.user_id=NEW.reviewer_id OR EXISTS (
            SELECT 1 FROM project_members m WHERE m.project_id=p.id
              AND m.user_id=NEW.reviewer_id AND m.role='editor'))
      ) THEN RAISE EXCEPTION 'Invalid Human pair boundary' USING ERRCODE='23514'; END IF;
      SELECT COALESCE(MAX(version),0) INTO last_version FROM raw_pair_reviews
        WHERE left_id=NEW.left_id AND right_id=NEW.right_id;
      IF NEW.version<>last_version+1 THEN
        RAISE EXCEPTION 'Pair version conflict' USING ERRCODE='23514'; END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER raw_pair_insert BEFORE INSERT ON raw_pair_reviews
      FOR EACH ROW EXECUTE FUNCTION raw_pair_insert_guard();
    CREATE TRIGGER raw_pair_session BEFORE INSERT ON raw_pair_reviews
      FOR EACH ROW EXECUTE FUNCTION raw_label_session_guard();
    CREATE TRIGGER raw_review_session BEFORE INSERT ON raw_lead_reviews
      FOR EACH ROW EXECUTE FUNCTION raw_label_session_guard();
    CREATE TRIGGER raw_pair_immutable BEFORE UPDATE OR DELETE ON raw_pair_reviews
      FOR EACH ROW EXECUTE FUNCTION raw_collection_immutable_guard();
    CREATE TRIGGER raw_pair_no_truncate BEFORE TRUNCATE ON raw_pair_reviews
      FOR EACH STATEMENT EXECUTE FUNCTION raw_collection_immutable_guard();
    """)


def downgrade():
    if (
        op.get_bind()
        .execute(
            sa.text(
                "SELECT EXISTS(SELECT 1 FROM raw_pair_reviews) OR "
                "EXISTS(SELECT 1 FROM raw_query_runs WHERE repeat_index>1)"
            )
        )
        .scalar()
    ):
        raise RuntimeError(
            "Repeat or pair evidence exists; archive and plan retention before downgrade"
        )
    op.execute("DROP TRIGGER raw_review_session ON raw_lead_reviews")
    op.execute("""
    CREATE OR REPLACE FUNCTION raw_query_definition_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF (NEW.benchmark_id,NEW.ordinal,NEW.source,NEW.keyword,NEW.query,
          NEW.requested_count,NEW.code_commit,NEW.created_at) IS DISTINCT FROM
         (OLD.benchmark_id,OLD.ordinal,OLD.source,OLD.keyword,OLD.query,
          OLD.requested_count,OLD.code_commit,OLD.created_at) THEN
        RAISE EXCEPTION 'Raw query definition is immutable' USING ERRCODE='23514';
      END IF;
      RETURN NEW;
    END $$;
    """)
    op.drop_constraint("ck_raw_run_repeat", "raw_query_runs", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_raw_run_repeat", "raw_query_runs", type_="unique")
    op.create_unique_constraint(
        op.f("uq_raw_run_query"),
        "raw_query_runs",
        ["benchmark_id", "source", "keyword"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("raw_query_runs", "repeat_index")
    op.drop_index(op.f("ix_raw_pair_reviews_left_id"), table_name="raw_pair_reviews")
    op.drop_table("raw_pair_reviews")
    op.execute("DROP FUNCTION raw_pair_insert_guard()")
    op.execute("DROP FUNCTION raw_label_session_guard()")
    # ### end Alembic commands ###
