"""Evidence bound DM template preparation"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "37945a503231"
down_revision = "1ea563b6ad2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lead_dm_preparations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column("choice_id", sa.Uuid(), nullable=False),
        sa.Column("choice_version", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("template_hash", sa.String(length=64), nullable=False),
        sa.Column("context_hash", sa.String(length=64), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "expires_at > created_at AND expires_at <= created_at + interval '7 days'",
            name="ck_dm_preparation_expiry",
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lead_dm_preparations_company_id"),
        "lead_dm_preparations",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lead_dm_preparations_project_id"),
        "lead_dm_preparations",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    op.execute("""
    CREATE FUNCTION dm_preparation_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP = 'DELETE' THEN
        IF NOT EXISTS (SELECT 1 FROM projects WHERE id=OLD.project_id) THEN RETURN OLD; END IF;
        RAISE EXCEPTION 'DM preparation is immutable' USING ERRCODE='23514';
      ELSIF TG_OP IN ('UPDATE','TRUNCATE') THEN
        RAISE EXCEPTION 'DM preparation is immutable' USING ERRCODE='23514';
      END IF;
      PERFORM 1 FROM projects WHERE id=NEW.project_id FOR UPDATE;
      IF NOT EXISTS (SELECT 1 FROM companies c JOIN projects p ON p.id=c.project_id
        JOIN users u ON u.id=NEW.actor_user_id JOIN destination_choice_events e
          ON e.company_id=c.id AND e.project_id=p.id
        WHERE c.id=NEW.company_id AND p.id=NEW.project_id AND e.id=NEW.choice_id
          AND e.event_type='SELECTED' AND e.version=NEW.choice_version
          AND e.version=(SELECT MAX(version) FROM destination_choice_events WHERE company_id=c.id)
          AND e.expires_at>now() AND NEW.expires_at<=e.expires_at
          AND (p.user_id=u.id OR EXISTS (SELECT 1 FROM project_members m
            WHERE m.project_id=p.id AND m.user_id=u.id AND m.role='editor'))) THEN
        RAISE EXCEPTION 'Invalid DM preparation binding or Human membership' USING ERRCODE='23514';
      END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER dm_preparation_append_guard BEFORE INSERT OR UPDATE OR DELETE
      ON lead_dm_preparations FOR EACH ROW EXECUTE FUNCTION dm_preparation_guard();
    CREATE TRIGGER dm_preparation_truncate_guard BEFORE TRUNCATE
      ON lead_dm_preparations FOR EACH STATEMENT EXECUTE FUNCTION dm_preparation_guard();
    """)


def downgrade():
    if op.get_bind().execute(sa.text("SELECT EXISTS(SELECT 1 FROM lead_dm_preparations)")).scalar():
        raise RuntimeError("DM preparation evidence exists; downgrade refused")
    op.execute("DROP TRIGGER dm_preparation_append_guard ON lead_dm_preparations")
    op.execute("DROP TRIGGER dm_preparation_truncate_guard ON lead_dm_preparations")
    op.execute("DROP FUNCTION dm_preparation_guard()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lead_dm_preparations_project_id"), table_name="lead_dm_preparations")
    op.drop_index(op.f("ix_lead_dm_preparations_company_id"), table_name="lead_dm_preparations")
    op.drop_table("lead_dm_preparations")
    # ### end Alembic commands ###
