"""external presence and bounded search ledger"""

import sqlalchemy as sa
from alembic import context, op
from sqlalchemy.dialects import postgresql

revision = "3c95eac42b10"
down_revision = "29d351ead7ae"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        "collection_jobs",
        sa.Column("presence_search_plan", postgresql.JSONB(), server_default="{}", nullable=False),
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_presences",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("platform", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("discovery_method", sa.String(length=30), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.String(length=100), nullable=False),
        sa.Column("identity_hash", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "status IN ('FOUND','NOT_FOUND','NOT_CHECKED','ERROR')", name="ck_presence_status"
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "platform", name="uq_presence_company_platform"),
    )
    op.create_index(
        op.f("ix_external_presences_company_id"), "external_presences", ["company_id"], unique=False
    )
    op.create_table(
        "external_presence_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("collection_job_id", sa.Uuid(), nullable=True),
        sa.Column("platform", sa.String(length=40), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("discovery_method", sa.String(length=30), nullable=False),
        sa.Column("association", sa.String(length=30), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["collection_job_id"], ["collection_jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_external_presence_evidence_collection_job_id"),
        "external_presence_evidence",
        ["collection_job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_presence_evidence_company_id"),
        "external_presence_evidence",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_presence_evidence_project_id"),
        "external_presence_evidence",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "external_presence_searches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("collection_job_id", sa.Uuid(), nullable=False),
        sa.Column("operation_job_id", sa.Uuid(), nullable=True),
        sa.Column("budget_job_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("platform", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["budget_job_id"], ["collection_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["collection_job_id"], ["collection_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["operation_job_id"], ["operation_jobs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "collection_job_id", "company_id", "platform", name="uq_presence_search"
        ),
    )
    op.create_index(
        op.f("ix_external_presence_searches_budget_job_id"),
        "external_presence_searches",
        ["budget_job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_presence_searches_collection_job_id"),
        "external_presence_searches",
        ["collection_job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_presence_searches_operation_job_id"),
        "external_presence_searches",
        ["operation_job_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    has_data = (
        op.get_bind()
        .execute(
            sa.text(
                "SELECT EXISTS(SELECT 1 FROM external_presences) OR "
                "EXISTS(SELECT 1 FROM external_presence_evidence) OR "
                "EXISTS(SELECT 1 FROM external_presence_searches)"
            )
        )
        .scalar()
    )
    if (
        has_data
        and context.get_x_argument(as_dictionary=True).get("allow_presence_data_loss") != "true"
    ):
        raise RuntimeError(
            "Export presence data before downgrade; explicit allow_presence_data_loss required"
        )
    op.drop_column("collection_jobs", "presence_search_plan")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_external_presence_searches_operation_job_id"),
        table_name="external_presence_searches",
    )
    op.drop_index(
        op.f("ix_external_presence_searches_collection_job_id"),
        table_name="external_presence_searches",
    )
    op.drop_index(
        op.f("ix_external_presence_searches_budget_job_id"), table_name="external_presence_searches"
    )
    op.drop_table("external_presence_searches")
    op.drop_index(
        op.f("ix_external_presence_evidence_project_id"), table_name="external_presence_evidence"
    )
    op.drop_index(
        op.f("ix_external_presence_evidence_company_id"), table_name="external_presence_evidence"
    )
    op.drop_index(
        op.f("ix_external_presence_evidence_collection_job_id"),
        table_name="external_presence_evidence",
    )
    op.drop_table("external_presence_evidence")
    op.drop_index(op.f("ix_external_presences_company_id"), table_name="external_presences")
    op.drop_table("external_presences")
    # ### end Alembic commands ###
