"""confirmed collection conditions"""

import sqlalchemy as sa
from alembic import context, op
from sqlalchemy.dialects import postgresql

revision = "62a91de74b20"
down_revision = "3c95eac42b10"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection_condition_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("collection_job_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("confirmed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "confirmed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version > 0", name="ck_condition_request_version"),
        sa.ForeignKeyConstraint(["collection_job_id"], ["collection_jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["confirmed_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "version", name="uq_condition_request_project_version"),
    )
    op.create_index(
        op.f("ix_collection_condition_requests_project_id"),
        "collection_condition_requests",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    count = op.get_bind().scalar(sa.text("SELECT count(*) FROM collection_condition_requests"))
    if (
        count
        and context.get_x_argument(as_dictionary=True).get("allow_condition_data_loss") != "true"
    ):
        raise RuntimeError(
            "Export confirmed conditions before downgrade; "
            "explicit allow_condition_data_loss=true required"
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_collection_condition_requests_project_id"),
        table_name="collection_condition_requests",
    )
    op.drop_table("collection_condition_requests")
    # ### end Alembic commands ###
