"""add scheduled search collection"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "840baf8a6ff1"
down_revision = "ca92f18e2e9a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_schedules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("region", sa.String(length=500), nullable=False),
        sa.Column("max_results", sa.Integer(), nullable=False),
        sa.Column("interval_hours", sa.Integer(), nullable=False),
        sa.Column("company_limit", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_enqueued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('serper', 'google_places')", name="ck_search_schedule_source"
        ),
        sa.CheckConstraint("company_limit BETWEEN 1 AND 100000", name="ck_search_schedule_limit"),
        sa.CheckConstraint("interval_hours BETWEEN 1 AND 720", name="ck_search_schedule_interval"),
        sa.CheckConstraint("max_results BETWEEN 1 AND 100", name="ck_search_schedule_max_results"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_search_schedules_next_run_at"), "search_schedules", ["next_run_at"], unique=False
    )
    op.create_index(
        op.f("ix_search_schedules_project_id"), "search_schedules", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_search_schedules_project_id"), table_name="search_schedules")
    op.drop_index(op.f("ix_search_schedules_next_run_at"), table_name="search_schedules")
    op.drop_table("search_schedules")
    # ### end Alembic commands ###
