"""track collection exclusions and timing"""

import sqlalchemy as sa
from alembic import op

revision = "9418ea575b6b"
down_revision = "a6eadf91f966"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collection_jobs",
        sa.Column("excluded_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "collection_jobs",
        sa.Column("processing_ms", sa.Integer(), server_default="0", nullable=False),
    )
    op.drop_constraint("ck_job_counts", "collection_jobs", type_="check")
    op.create_check_constraint(
        "ck_job_counts",
        "collection_jobs",
        "found_count >= 0 AND saved_count >= 0 AND duplicate_count >= 0 AND "
        "excluded_count >= 0 AND error_count >= 0 AND processing_ms >= 0",
    )
    op.alter_column("collection_jobs", "excluded_count", server_default=None)
    op.alter_column("collection_jobs", "processing_ms", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_job_counts", "collection_jobs", type_="check")
    op.create_check_constraint(
        "ck_job_counts",
        "collection_jobs",
        "found_count >= 0 AND saved_count >= 0 AND duplicate_count >= 0 AND error_count >= 0",
    )
    op.drop_column("collection_jobs", "processing_ms")
    op.drop_column("collection_jobs", "excluded_count")
    # ### end Alembic commands ###
