"""add web analysis fields"""

import sqlalchemy as sa
from alembic import op

revision = "9acfc2e2665c"
down_revision = "b04a735ef207"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    empty = sa.text("''")
    for name, type_ in (
        ("prefecture", sa.String(length=20)),
        ("city", sa.String(length=200)),
        ("contact_url", sa.Text()),
        ("instagram_url", sa.Text()),
        ("x_url", sa.Text()),
        ("tiktok_url", sa.Text()),
        ("facebook_url", sa.Text()),
        ("youtube_url", sa.Text()),
        ("line_url", sa.Text()),
        ("business_summary", sa.Text()),
        ("website_text", sa.Text()),
        ("analysis_error", sa.String(length=500)),
    ):
        op.add_column("companies", sa.Column(name, type_, server_default=empty, nullable=False))
    op.add_column(
        "companies",
        sa.Column(
            "analysis_status", sa.String(length=30), server_default="pending", nullable=False
        ),
    )
    op.add_column(
        "companies",
        sa.Column("is_aggregator", sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.add_column("companies", sa.Column("duplicate_of_id", sa.Uuid(), nullable=True))
    op.add_column("companies", sa.Column("scraped_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(
        op.f("ix_companies_analysis_status"), "companies", ["analysis_status"], unique=False
    )
    op.create_index(
        op.f("ix_companies_duplicate_of_id"), "companies", ["duplicate_of_id"], unique=False
    )
    op.create_foreign_key(
        "fk_companies_duplicate_of_id",
        "companies",
        "companies",
        ["duplicate_of_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_check_constraint(
        "ck_company_analysis_status",
        "companies",
        "analysis_status IN ('pending', 'running', 'completed', 'failed', 'skipped', "
        "'duplicate', 'excluded')",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_company_analysis_status", "companies", type_="check")
    op.drop_constraint("fk_companies_duplicate_of_id", "companies", type_="foreignkey")
    op.drop_index(op.f("ix_companies_duplicate_of_id"), table_name="companies")
    op.drop_index(op.f("ix_companies_analysis_status"), table_name="companies")
    op.drop_column("companies", "scraped_at")
    op.drop_column("companies", "duplicate_of_id")
    op.drop_column("companies", "is_aggregator")
    op.drop_column("companies", "analysis_error")
    op.drop_column("companies", "analysis_status")
    op.drop_column("companies", "website_text")
    op.drop_column("companies", "business_summary")
    op.drop_column("companies", "line_url")
    op.drop_column("companies", "youtube_url")
    op.drop_column("companies", "facebook_url")
    op.drop_column("companies", "tiktok_url")
    op.drop_column("companies", "x_url")
    op.drop_column("companies", "instagram_url")
    op.drop_column("companies", "contact_url")
    op.drop_column("companies", "city")
    op.drop_column("companies", "prefecture")
    # ### end Alembic commands ###
