"""add contact suppression and quality"""

import sqlalchemy as sa
from alembic import op

revision = "a6eadf91f966"
down_revision = "47cc28138178"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "suppression_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("domain", sa.String(length=253), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("phone", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_suppression_entries_domain"), "suppression_entries", ["domain"], unique=False
    )
    op.create_index(
        op.f("ix_suppression_entries_email"), "suppression_entries", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_suppression_entries_phone"), "suppression_entries", ["phone"], unique=False
    )
    op.create_index(
        op.f("ix_suppression_entries_project_id"),
        "suppression_entries",
        ["project_id"],
        unique=False,
    )
    op.add_column(
        "companies",
        sa.Column("do_not_contact", sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.add_column(
        "companies",
        sa.Column("exclusion_reason", sa.String(length=500), server_default="", nullable=False),
    )
    op.add_column(
        "companies",
        sa.Column(
            "contact_quality_status", sa.String(length=20), server_default="unknown", nullable=False
        ),
    )
    op.add_column(
        "companies", sa.Column("contact_source_url", sa.Text(), server_default="", nullable=False)
    )
    op.add_column(
        "companies", sa.Column("contact_checked_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        op.f("ix_companies_do_not_contact"), "companies", ["do_not_contact"], unique=False
    )
    for column in (
        "do_not_contact",
        "exclusion_reason",
        "contact_quality_status",
        "contact_source_url",
    ):
        op.alter_column("companies", column, server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_companies_do_not_contact"), table_name="companies")
    op.drop_column("companies", "contact_checked_at")
    op.drop_column("companies", "contact_source_url")
    op.drop_column("companies", "contact_quality_status")
    op.drop_column("companies", "exclusion_reason")
    op.drop_column("companies", "do_not_contact")
    op.drop_index(op.f("ix_suppression_entries_project_id"), table_name="suppression_entries")
    op.drop_index(op.f("ix_suppression_entries_phone"), table_name="suppression_entries")
    op.drop_index(op.f("ix_suppression_entries_email"), table_name="suppression_entries")
    op.drop_index(op.f("ix_suppression_entries_domain"), table_name="suppression_entries")
    op.drop_table("suppression_entries")
    # ### end Alembic commands ###
