"""add company collection foundation"""

import sqlalchemy as sa
from alembic import op

revision = "b04a735ef207"
down_revision = "c04b62783e12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("keyword", sa.String(length=500), nullable=False),
        sa.Column("region", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("found_count", sa.Integer(), nullable=False),
        sa.Column("saved_count", sa.Integer(), nullable=False),
        sa.Column("duplicate_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "source IN ('serper', 'google_places', 'url', 'csv')", name="ck_job_source"
        ),
        sa.CheckConstraint("status IN ('running', 'completed', 'failed')", name="ck_job_status"),
        sa.CheckConstraint(
            "found_count >= 0 AND saved_count >= 0 AND duplicate_count >= 0 AND error_count >= 0",
            name="ck_job_counts",
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_collection_jobs_project_id"), "collection_jobs", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_collection_jobs_status"), "collection_jobs", ["status"], unique=False)
    op.create_table(
        "companies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("company_name", sa.String(length=500), nullable=False),
        sa.Column("website_url", sa.Text(), nullable=True),
        sa.Column("domain", sa.String(length=253), nullable=True),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("phone", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("source_keyword", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('serper', 'google_places', 'url', 'csv')", name="ck_company_source"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "domain", name="uq_company_project_domain"),
        sa.UniqueConstraint("project_id", "website_url", name="uq_company_project_website"),
    )
    op.create_index(op.f("ix_companies_project_id"), "companies", ["project_id"], unique=False)
    op.create_index(
        "uq_company_project_name_address",
        "companies",
        ["project_id", "company_name", "address"],
        unique=True,
        postgresql_where=sa.text("address <> ''"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_company_project_name_address",
        table_name="companies",
        postgresql_where=sa.text("address <> ''"),
    )
    op.drop_index(op.f("ix_companies_project_id"), table_name="companies")
    op.drop_table("companies")
    op.drop_index(op.f("ix_collection_jobs_status"), table_name="collection_jobs")
    op.drop_index(op.f("ix_collection_jobs_project_id"), table_name="collection_jobs")
    op.drop_table("collection_jobs")
    # ### end Alembic commands ###
