"""add operation job leases"""

import sqlalchemy as sa
from alembic import op

revision = "b2ff18dc8e97"
down_revision = "67aecfde853d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "operation_jobs",
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column("operation_jobs", sa.Column("worker_id", sa.Uuid(), nullable=True))
    op.add_column(
        "operation_jobs", sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        op.f("ix_operation_jobs_lease_expires_at"),
        "operation_jobs",
        ["lease_expires_at"],
        unique=False,
    )
    op.create_check_constraint(
        "ck_operation_job_attempt_count", "operation_jobs", "attempt_count >= 0"
    )
    op.execute(
        """
        UPDATE operation_jobs
        SET status = CASE WHEN cancel_requested THEN 'cancelled' ELSE 'queued' END,
            started_at = NULL,
            finished_at = CASE WHEN cancel_requested THEN now() ELSE NULL END,
            total_count = CASE WHEN cancel_requested THEN total_count ELSE 0 END,
            processed_count = CASE WHEN cancel_requested THEN processed_count ELSE 0 END,
            success_count = CASE WHEN cancel_requested THEN success_count ELSE 0 END,
            failed_count = CASE WHEN cancel_requested THEN failed_count ELSE 0 END,
            error_message = CASE
                WHEN cancel_requested THEN error_message
                ELSE 'Migration後に処理を再試行します。'
            END
        WHERE status = 'running'
        """
    )
    op.alter_column("operation_jobs", "attempt_count", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_operation_job_attempt_count", "operation_jobs", type_="check")
    op.drop_index(op.f("ix_operation_jobs_lease_expires_at"), table_name="operation_jobs")
    op.drop_column("operation_jobs", "lease_expires_at")
    op.drop_column("operation_jobs", "worker_id")
    op.drop_column("operation_jobs", "attempt_count")
    # ### end Alembic commands ###
