"""add company followups and activities"""

import sqlalchemy as sa
from alembic import op

revision = "b6505cc5fb84"
down_revision = "1129fe32eda3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("activity_type", sa.String(length=30), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "activity_type IN ('note', 'call', 'email', 'form', 'sns', 'meeting', 'status_change')",
            name="ck_activity_type",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_activities_company_id"), "activities", ["company_id"], unique=False)
    op.add_column(
        "companies", sa.Column("next_followup_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        op.f("ix_companies_next_followup_at"), "companies", ["next_followup_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_companies_next_followup_at"), table_name="companies")
    op.drop_column("companies", "next_followup_at")
    op.drop_index(op.f("ix_activities_company_id"), table_name="activities")
    op.drop_table("activities")
    # ### end Alembic commands ###
