"""add company assignee"""

import sqlalchemy as sa
from alembic import op

revision = "b9f31544014d"
down_revision = "11d84c5dfff0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies",
        sa.Column("assignee", sa.String(length=200), server_default="", nullable=False),
    )
    op.create_index(op.f("ix_companies_assignee"), "companies", ["assignee"], unique=False)
    op.alter_column("companies", "assignee", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_companies_assignee"), table_name="companies")
    op.drop_column("companies", "assignee")
    # ### end Alembic commands ###
