"""add operation failure acknowledgement"""

import sqlalchemy as sa
from alembic import op

revision = "ca92f18e2e9a"
down_revision = "b2ff18dc8e97"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "operation_jobs", sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operation_jobs", "acknowledged_at")
    # ### end Alembic commands ###
