"""human destination purpose review evidence"""

import sqlalchemy as sa
from alembic import op

revision = "e49867e60dcd"
down_revision = "06a2f819c310"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "destination_review_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("destination_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=20), nullable=False),
        sa.Column("purpose", sa.String(length=30), nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("evidence_excerpt", sa.String(length=1000), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("canonicalization_version", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('CONFIRMED','REVOKED')", name="ck_destination_review_event"
        ),
        sa.CheckConstraint(
            "expires_at > created_at AND expires_at <= created_at + interval '7 days'",
            name="ck_destination_review_expiry",
        ),
        sa.CheckConstraint(
            "purpose IN ('general','business','partnership','sales','support',"
            "'recruitment','reservation','unknown')",
            name="ck_destination_review_purpose",
        ),
        sa.CheckConstraint(
            "scope IN ('company','location','group','unknown')", name="ck_destination_review_scope"
        ),
        sa.CheckConstraint("version > 0", name="ck_destination_review_version"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id", "destination_id", "version", name="uq_destination_review_version"
        ),
    )
    op.create_index(
        op.f("ix_destination_review_events_company_id"),
        "destination_review_events",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_destination_review_events_destination_id"),
        "destination_review_events",
        ["destination_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_destination_review_events_project_id"),
        "destination_review_events",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    op.execute("""
    CREATE FUNCTION destination_review_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE last_version integer;
    BEGIN
      IF TG_OP = 'TRUNCATE' THEN
        RAISE EXCEPTION 'Destination evidence is append only' USING ERRCODE='23514';
      ELSIF TG_OP = 'DELETE' THEN
        IF NOT EXISTS (SELECT 1 FROM projects WHERE id=OLD.project_id) THEN RETURN OLD; END IF;
        RAISE EXCEPTION 'Destination evidence is append only' USING ERRCODE='23514';
      ELSIF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION 'Destination evidence is append only' USING ERRCODE='23514';
      END IF;
      PERFORM 1 FROM projects WHERE id=NEW.project_id FOR UPDATE;
      IF NOT EXISTS (SELECT 1 FROM companies c
        JOIN lead_destination_links l ON l.company_id=c.id
        JOIN contact_destinations d ON d.id=l.destination_id
        JOIN projects p ON p.id=c.project_id
        JOIN users u ON u.id=NEW.actor_user_id
        WHERE c.id=NEW.company_id AND c.project_id=NEW.project_id
          AND d.id=NEW.destination_id AND d.project_id=NEW.project_id AND d.active
          AND (p.user_id=u.id OR EXISTS (SELECT 1 FROM project_members m
             WHERE m.project_id=p.id AND m.user_id=u.id AND m.role='editor'))) THEN
        RAISE EXCEPTION 'Invalid review project or Human membership' USING ERRCODE='23514';
      END IF;
      SELECT COALESCE(MAX(version),0) INTO last_version FROM destination_review_events
        WHERE company_id=NEW.company_id AND destination_id=NEW.destination_id;
      IF NEW.version <> last_version+1 THEN
        RAISE EXCEPTION 'Review version conflict' USING ERRCODE='23514';
      END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER destination_review_append_guard BEFORE INSERT OR UPDATE OR DELETE
      ON destination_review_events FOR EACH ROW EXECUTE FUNCTION destination_review_guard();
    CREATE TRIGGER destination_review_truncate_guard BEFORE TRUNCATE
      ON destination_review_events FOR EACH STATEMENT EXECUTE FUNCTION destination_review_guard();
    """)


def downgrade():
    if (
        op.get_bind()
        .execute(sa.text("SELECT EXISTS(SELECT 1 FROM destination_review_events)"))
        .scalar()
    ):
        raise RuntimeError("Destination review evidence exists; downgrade refused")
    op.execute(
        "DROP TRIGGER IF EXISTS destination_review_append_guard ON destination_review_events"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS destination_review_truncate_guard ON destination_review_events"
    )
    op.execute("DROP FUNCTION IF EXISTS destination_review_guard()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_destination_review_events_project_id"), table_name="destination_review_events"
    )
    op.drop_index(
        op.f("ix_destination_review_events_destination_id"), table_name="destination_review_events"
    )
    op.drop_index(
        op.f("ix_destination_review_events_company_id"), table_name="destination_review_events"
    )
    op.drop_table("destination_review_events")
    # ### end Alembic commands ###
