"""add inbound email replies"""

import sqlalchemy as sa
from alembic import op

revision = "e6ab1a60add4"
down_revision = "f62b9d0e41ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inbound_mail_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=320), nullable=False),
        sa.Column("password_ciphertext", sa.Text(), nullable=False),
        sa.Column("mailbox", sa.String(length=200), nullable=False),
        sa.Column("use_ssl", sa.Boolean(), nullable=False),
        sa.Column("timeout_seconds", sa.Float(), nullable=False),
        sa.Column("poll_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("last_polled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=False),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "poll_interval_seconds BETWEEN 60 AND 86400",
            name="ck_inbound_mail_settings_poll_interval",
        ),
        sa.ForeignKeyConstraint(["updated_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inbound_mail_settings_updated_by_user_id"),
        "inbound_mail_settings",
        ["updated_by_user_id"],
        unique=False,
    )
    op.create_table(
        "inbound_emails",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mailbox_uid", sa.String(length=100), nullable=False),
        sa.Column("message_id", sa.String(length=500), nullable=False),
        sa.Column("sender_email", sa.String(length=320), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("preview", sa.String(length=1000), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("match_type", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "match_type IN ('company_email', 'contact_person', 'unmatched')",
            name="ck_inbound_email_match_type",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mailbox_uid", name="uq_inbound_email_mailbox_uid"),
    )
    op.create_index(
        op.f("ix_inbound_emails_company_id"), "inbound_emails", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_inbound_emails_received_at"), "inbound_emails", ["received_at"], unique=False
    )
    op.create_index(
        op.f("ix_inbound_emails_sender_email"), "inbound_emails", ["sender_email"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inbound_emails_sender_email"), table_name="inbound_emails")
    op.drop_index(op.f("ix_inbound_emails_received_at"), table_name="inbound_emails")
    op.drop_index(op.f("ix_inbound_emails_company_id"), table_name="inbound_emails")
    op.drop_table("inbound_emails")
    op.drop_index(
        op.f("ix_inbound_mail_settings_updated_by_user_id"), table_name="inbound_mail_settings"
    )
    op.drop_table("inbound_mail_settings")
    # ### end Alembic commands ###
